//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zongsoft.Data.PostgreSql.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zongsoft.Data.PostgreSql.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Auto-Prepare Minimum Usages 的本地化字符串。
        /// </summary>
        internal static string PostgreSql_Settings_AutoPrepareMinUsages {
            get {
                return ResourceManager.GetString("PostgreSql.Settings.AutoPrepareMinUsages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The minimum number of usages an SQL statement is used before it&apos;s automatically prepared. Defaults to 5. 的本地化字符串。
        /// </summary>
        internal static string PostgreSql_Settings_AutoPrepareMinUsages_Description {
            get {
                return ResourceManager.GetString("PostgreSql.Settings.AutoPrepareMinUsages.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Certificate Secret 的本地化字符串。
        /// </summary>
        internal static string PostgreSql_Settings_CertificateSecret {
            get {
                return ResourceManager.GetString("PostgreSql.Settings.CertificateSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password for a key for a client certificate. 的本地化字符串。
        /// </summary>
        internal static string PostgreSql_Settings_CertificateSecret_Description {
            get {
                return ResourceManager.GetString("PostgreSql.Settings.CertificateSecret.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check Certificate Revocation 的本地化字符串。
        /// </summary>
        internal static string PostgreSql_Settings_CheckCertificateRevocation {
            get {
                return ResourceManager.GetString("PostgreSql.Settings.CheckCertificateRevocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Whether to check the certificate revocation list during authentication. Defaults to false. 的本地化字符串。
        /// </summary>
        internal static string PostgreSql_Settings_CheckCertificateRevocation_Description {
            get {
                return ResourceManager.GetString("PostgreSql.Settings.CheckCertificateRevocation.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Client 的本地化字符串。
        /// </summary>
        internal static string PostgreSql_Settings_Client {
            get {
                return ResourceManager.GetString("PostgreSql.Settings.Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connection Idle Lifetime 的本地化字符串。
        /// </summary>
        internal static string PostgreSql_Settings_ConnectionIdleLifetime {
            get {
                return ResourceManager.GetString("PostgreSql.Settings.ConnectionIdleLifetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The time to wait before closing unused connections in the pool if the count of all connections exceeds MinimumPoolSize. 的本地化字符串。
        /// </summary>
        internal static string PostgreSql_Settings_ConnectionIdleLifetime_Description {
            get {
                return ResourceManager.GetString("PostgreSql.Settings.ConnectionIdleLifetime.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connection Lifetime 的本地化字符串。
        /// </summary>
        internal static string PostgreSql_Settings_ConnectionLifetime {
            get {
                return ResourceManager.GetString("PostgreSql.Settings.ConnectionLifetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The total maximum lifetime of connections (in seconds), Defaults to 3600 seconds(1 hour).
        ///Connections which have exceeded this value will be destroyed instead of returned from the pool.
        ///This is useful in clustered configurations to force load balancing between a running server and a server just brought online. It can also be useful to prevent runaway memory growth of connections at the PostgreSQL server side, because in some cases very long lived connections slowly consume more and more memory over time. 的本地化字符串。
        /// </summary>
        internal static string PostgreSql_Settings_ConnectionLifetime_Description {
            get {
                return ResourceManager.GetString("PostgreSql.Settings.ConnectionLifetime.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connection Pruning Interval 的本地化字符串。
        /// </summary>
        internal static string PostgreSql_Settings_ConnectionPruningInterval {
            get {
                return ResourceManager.GetString("PostgreSql.Settings.ConnectionPruningInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 How many seconds the pool waits before attempting to prune idle connections that are beyond idle lifetime. 的本地化字符串。
        /// </summary>
        internal static string PostgreSql_Settings_ConnectionPruningInterval_Description {
            get {
                return ResourceManager.GetString("PostgreSql.Settings.ConnectionPruningInterval.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Database 的本地化字符串。
        /// </summary>
        internal static string PostgreSql_Settings_Database {
            get {
                return ResourceManager.GetString("PostgreSql.Settings.Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Encoding 的本地化字符串。
        /// </summary>
        internal static string PostgreSql_Settings_Encoding {
            get {
                return ResourceManager.GetString("PostgreSql.Settings.Encoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error Detailed 的本地化字符串。
        /// </summary>
        internal static string PostgreSql_Settings_ErrorDetailed {
            get {
                return ResourceManager.GetString("PostgreSql.Settings.ErrorDetailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 When enabled, PostgreSQL error and notice details are included on PostgresException.Detail and PostgresNotice.Detail. These can contain sensitive data. 的本地化字符串。
        /// </summary>
        internal static string PostgreSql_Settings_ErrorDetailed_Description {
            get {
                return ResourceManager.GetString("PostgreSql.Settings.ErrorDetailed.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 KeepAlive 的本地化字符串。
        /// </summary>
        internal static string PostgreSql_Settings_KeepAlive {
            get {
                return ResourceManager.GetString("PostgreSql.Settings.KeepAlive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The number of seconds of connection inactivity before client sends a keepalive query. Defaults is 0 to disable. 的本地化字符串。
        /// </summary>
        internal static string PostgreSql_Settings_KeepAlive_Description {
            get {
                return ResourceManager.GetString("PostgreSql.Settings.KeepAlive.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LoadBalance Enabled 的本地化字符串。
        /// </summary>
        internal static string PostgreSql_Settings_LoadBalanceEnabled {
            get {
                return ResourceManager.GetString("PostgreSql.Settings.LoadBalanceEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enables balancing between multiple hosts by round-robin. 的本地化字符串。
        /// </summary>
        internal static string PostgreSql_Settings_LoadBalanceEnabled_Description {
            get {
                return ResourceManager.GetString("PostgreSql.Settings.LoadBalanceEnabled.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LoadBalance Lifetime 的本地化字符串。
        /// </summary>
        internal static string PostgreSql_Settings_LoadBalanceLifetime {
            get {
                return ResourceManager.GetString("PostgreSql.Settings.LoadBalanceLifetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Controls for how long the host&apos;s cached state will be considered as valid. 的本地化字符串。
        /// </summary>
        internal static string PostgreSql_Settings_LoadBalanceLifetime_Description {
            get {
                return ResourceManager.GetString("PostgreSql.Settings.LoadBalanceLifetime.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maximum Auto-Prepare 的本地化字符串。
        /// </summary>
        internal static string PostgreSql_Settings_MaxAutoPrepare {
            get {
                return ResourceManager.GetString("PostgreSql.Settings.MaxAutoPrepare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The maximum number SQL statements that can be automatically prepared at any given point. Beyond this number the least-recently-used statement will be recycled. Zero (the default) disables automatic preparation. 的本地化字符串。
        /// </summary>
        internal static string PostgreSql_Settings_MaxAutoPrepare_Description {
            get {
                return ResourceManager.GetString("PostgreSql.Settings.MaxAutoPrepare.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maximum Pool Size 的本地化字符串。
        /// </summary>
        internal static string PostgreSql_Settings_MaximumPoolSize {
            get {
                return ResourceManager.GetString("PostgreSql.Settings.MaximumPoolSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minimum Pool Size 的本地化字符串。
        /// </summary>
        internal static string PostgreSql_Settings_MinimumPoolSize {
            get {
                return ResourceManager.GetString("PostgreSql.Settings.MinimumPoolSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Multiplexing 的本地化字符串。
        /// </summary>
        internal static string PostgreSql_Settings_Multiplexing {
            get {
                return ResourceManager.GetString("PostgreSql.Settings.Multiplexing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enables multiplexing, which allows more efficient use of connections. 的本地化字符串。
        /// </summary>
        internal static string PostgreSql_Settings_Multiplexing_Description {
            get {
                return ResourceManager.GetString("PostgreSql.Settings.Multiplexing.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Passfile 的本地化字符串。
        /// </summary>
        internal static string PostgreSql_Settings_Passfile {
            get {
                return ResourceManager.GetString("PostgreSql.Settings.Passfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Path to a PostgreSQL password file (PGPASSFILE), from which the password would be taken. 的本地化字符串。
        /// </summary>
        internal static string PostgreSql_Settings_Passfile_Description {
            get {
                return ResourceManager.GetString("PostgreSql.Settings.Passfile.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password 的本地化字符串。
        /// </summary>
        internal static string PostgreSql_Settings_Password {
            get {
                return ResourceManager.GetString("PostgreSql.Settings.Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pooling 的本地化字符串。
        /// </summary>
        internal static string PostgreSql_Settings_Pooling {
            get {
                return ResourceManager.GetString("PostgreSql.Settings.Pooling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Port 的本地化字符串。
        /// </summary>
        internal static string PostgreSql_Settings_Port {
            get {
                return ResourceManager.GetString("PostgreSql.Settings.Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Root Certificate 的本地化字符串。
        /// </summary>
        internal static string PostgreSql_Settings_RootCertificate {
            get {
                return ResourceManager.GetString("PostgreSql.Settings.RootCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Location of a CA certificate used to validate the server certificate. 的本地化字符串。
        /// </summary>
        internal static string PostgreSql_Settings_RootCertificate_Description {
            get {
                return ResourceManager.GetString("PostgreSql.Settings.RootCertificate.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Server 的本地化字符串。
        /// </summary>
        internal static string PostgreSql_Settings_Server {
            get {
                return ResourceManager.GetString("PostgreSql.Settings.Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SSL Certificate 的本地化字符串。
        /// </summary>
        internal static string PostgreSql_Settings_SslCertificate {
            get {
                return ResourceManager.GetString("PostgreSql.Settings.SslCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Location of a client certificate to be sent to the server. 的本地化字符串。
        /// </summary>
        internal static string PostgreSql_Settings_SslCertificate_Description {
            get {
                return ResourceManager.GetString("PostgreSql.Settings.SslCertificate.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SSL Key 的本地化字符串。
        /// </summary>
        internal static string PostgreSql_Settings_SslKey {
            get {
                return ResourceManager.GetString("PostgreSql.Settings.SslKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Location of a client key for a client certificate to be sent to the server. 的本地化字符串。
        /// </summary>
        internal static string PostgreSql_Settings_SslKey_Description {
            get {
                return ResourceManager.GetString("PostgreSql.Settings.SslKey.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SSL Mode 的本地化字符串。
        /// </summary>
        internal static string PostgreSql_Settings_SslMode {
            get {
                return ResourceManager.GetString("PostgreSql.Settings.SslMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Controls whether SSL is required, disabled or preferred, depending on server support. 的本地化字符串。
        /// </summary>
        internal static string PostgreSql_Settings_SslMode_Description {
            get {
                return ResourceManager.GetString("PostgreSql.Settings.SslMode.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Timeout 的本地化字符串。
        /// </summary>
        internal static string PostgreSql_Settings_Timeout {
            get {
                return ResourceManager.GetString("PostgreSql.Settings.Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Timezone 的本地化字符串。
        /// </summary>
        internal static string PostgreSql_Settings_Timezone {
            get {
                return ResourceManager.GetString("PostgreSql.Settings.Timezone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The PostgreSQL session timezone, in Olson/IANA database format. 的本地化字符串。
        /// </summary>
        internal static string PostgreSql_Settings_Timezone_Description {
            get {
                return ResourceManager.GetString("PostgreSql.Settings.Timezone.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User Name 的本地化字符串。
        /// </summary>
        internal static string PostgreSql_Settings_UserName {
            get {
                return ResourceManager.GetString("PostgreSql.Settings.UserName", resourceCulture);
            }
        }
    }
}
