//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zongsoft.Messaging.ZeroMQ.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zongsoft.Messaging.ZeroMQ.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid server port format: {0} 的本地化字符串。
        /// </summary>
        internal static string ServerOptions_InvalidPortFormat_Message {
            get {
                return ResourceManager.GetString("ServerOptions.InvalidPortFormat.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Client 的本地化字符串。
        /// </summary>
        internal static string ZeroMQ_Settings_Client {
            get {
                return ResourceManager.GetString("ZeroMQ.Settings.Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Filter 的本地化字符串。
        /// </summary>
        internal static string ZeroMQ_Settings_Filter {
            get {
                return ResourceManager.GetString("ZeroMQ.Settings.Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Acceptable sender instance identifiers, multiple identifiers separated by commas. Messages sent by this instance are not accepted by default.
        ///
        ///• Set to asterisk(*) if you need to accept messages from all (including this instance) senders;
        ///• Set to dot(.) or (~) if only messages from the sender of this instance are accepted ;
        ///• If you need to reject messages from the specified instance sender, follow the instance identifier with an exclamation mark (e.g. !1234, !5678). 的本地化字符串。
        /// </summary>
        internal static string ZeroMQ_Settings_Filter_Description {
            get {
                return ResourceManager.GetString("ZeroMQ.Settings.Filter.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Group 的本地化字符串。
        /// </summary>
        internal static string ZeroMQ_Settings_Group {
            get {
                return ResourceManager.GetString("ZeroMQ.Settings.Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A message queue group identifier is a unit of message isolation. 的本地化字符串。
        /// </summary>
        internal static string ZeroMQ_Settings_Group_Description {
            get {
                return ResourceManager.GetString("ZeroMQ.Settings.Group.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Heartbeat 的本地化字符串。
        /// </summary>
        internal static string ZeroMQ_Settings_Heartbeat {
            get {
                return ResourceManager.GetString("ZeroMQ.Settings.Heartbeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Heartbeat interval for maintaining network connection. The default value is 10 seconds. 的本地化字符串。
        /// </summary>
        internal static string ZeroMQ_Settings_Heartbeat_Description {
            get {
                return ResourceManager.GetString("ZeroMQ.Settings.Heartbeat.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Instance 的本地化字符串。
        /// </summary>
        internal static string ZeroMQ_Settings_Instance {
            get {
                return ResourceManager.GetString("ZeroMQ.Settings.Instance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The instance identifier of the message queue. Each sent message carries the instance identifier to which it belongs, the message receiver can determine the sender based on the instance identifier. Defaults to auto-generate. 的本地化字符串。
        /// </summary>
        internal static string ZeroMQ_Settings_Instance_Description {
            get {
                return ResourceManager.GetString("ZeroMQ.Settings.Instance.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Port 的本地化字符串。
        /// </summary>
        internal static string ZeroMQ_Settings_Port {
            get {
                return ResourceManager.GetString("ZeroMQ.Settings.Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Port number of the ZeroMQ message queue server. The default value is 7969. 的本地化字符串。
        /// </summary>
        internal static string ZeroMQ_Settings_Port_Description {
            get {
                return ResourceManager.GetString("ZeroMQ.Settings.Port.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Server 的本地化字符串。
        /// </summary>
        internal static string ZeroMQ_Settings_Server {
            get {
                return ResourceManager.GetString("ZeroMQ.Settings.Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Timeout 的本地化字符串。
        /// </summary>
        internal static string ZeroMQ_Settings_Timeout {
            get {
                return ResourceManager.GetString("ZeroMQ.Settings.Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Topic 的本地化字符串。
        /// </summary>
        internal static string ZeroMQ_Settings_Topic {
            get {
                return ResourceManager.GetString("ZeroMQ.Settings.Topic", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Failed to acquire queue exchange information from the &apos;{0}:{1}&apos; server. 的本地化字符串。
        /// </summary>
        internal static string ZeroQueue_ExchangeUnavailable_Message {
            get {
                return ResourceManager.GetString("ZeroQueue.ExchangeUnavailable.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The ZeroMQ publisher has not been initialized. 的本地化字符串。
        /// </summary>
        internal static string ZeroQueue_PublisherUninitialized_Message {
            get {
                return ResourceManager.GetString("ZeroQueue.PublisherUninitialized.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The ZeroMQ discovery response is invalid. 的本地化字符串。
        /// </summary>
        internal static string ZeroQueue_DiscoveryInvalid_Message {
            get {
                return ResourceManager.GetString("ZeroQueue.DiscoveryInvalid.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The ZeroMQ server discovery operation timed out. 的本地化字符串。
        /// </summary>
        internal static string ZeroQueue_DiscoveryTimeout_Message {
            get {
                return ResourceManager.GetString("ZeroQueue.DiscoveryTimeout.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The ZeroMQ broker did not confirm whether the message was accepted before the control operation timed out. 的本地化字符串。
        /// </summary>
        internal static string ZeroQueue_ControlTimeout_Message {
            get {
                return ResourceManager.GetString("ZeroQueue.ControlTimeout.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The topic of an active ZeroMQ subscription cannot be changed. 的本地化字符串。
        /// </summary>
        internal static string ZeroQueue_SubscriptionTopicImmutable_Message {
            get {
                return ResourceManager.GetString("ZeroQueue.SubscriptionTopicImmutable.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The required server address is missing in the connection settings. 的本地化字符串。
        /// </summary>
        internal static string ZeroQueue_ServerRequired_Message {
            get {
                return ResourceManager.GetString("ZeroQueue.ServerRequired.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The ZeroMQ broker reliable control channel is unavailable. Configure a message storage on the server. 的本地化字符串。
        /// </summary>
        internal static string ZeroQueue_ControlUnavailable_Message {
            get {
                return ResourceManager.GetString("ZeroQueue.ControlUnavailable.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The message storage cannot be changed while the ZeroMQ server is running. 的本地化字符串。
        /// </summary>
        internal static string ZeroQueueServer_StorageImmutable_Message {
            get {
                return ResourceManager.GetString("ZeroQueueServer.StorageImmutable.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The accepted least-once message &apos;{0}&apos; expired before a consumer acknowledged it. 的本地化字符串。
        /// </summary>
        internal static string ZeroQueue_ReliableExpired_Message {
            get {
                return ResourceManager.GetString("ZeroQueue.ReliableExpired.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The ZeroMQ reliability protocol failed with error code &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string ZeroQueue_ReliableProtocolError_Message {
            get {
                return ResourceManager.GetString("ZeroQueue.ReliableProtocolError.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The reliable message entry &apos;{0}&apos; in the &apos;{1}&apos; storage is invalid and was ignored. 的本地化字符串。
        /// </summary>
        internal static string ZeroQueue_ReliableEntryInvalid_Message {
            get {
                return ResourceManager.GetString("ZeroQueue.ReliableEntryInvalid.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The &apos;{0}&apos; message storage failed to persist message &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        internal static string ZeroQueue_StorageSetFailed_Message {
            get {
                return ResourceManager.GetString("ZeroQueue.StorageSetFailed.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The &apos;{0}&apos; message storage failed to remove message &apos;{1}&apos;; the operation will be retried. 的本地化字符串。
        /// </summary>
        internal static string ZeroQueue_StorageRemoveFailed_Message {
            get {
                return ResourceManager.GetString("ZeroQueue.StorageRemoveFailed.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 A message queue must be specified before opening or sending events. 的本地化字符串。
        /// </summary>
        internal static string ZeroQueueEventChannel_QueueRequired_Message {
            get {
                return ResourceManager.GetString("ZeroQueueEventChannel.QueueRequired.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Data ports must be between 0 and {0}. 的本地化字符串。
        /// </summary>
        internal static string ZeroQueueServer_DataPortOutOfRange_Message {
            get {
                return ResourceManager.GetString("ZeroQueueServer.DataPortOutOfRange.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The incoming and outgoing ports must be different. 的本地化字符串。
        /// </summary>
        internal static string ZeroQueueServer_DataPortsConflict_Message {
            get {
                return ResourceManager.GetString("ZeroQueueServer.DataPortsConflict.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 A data port cannot equal the discovery port. 的本地化字符串。
        /// </summary>
        internal static string ZeroQueueServer_DiscoveryPortConflict_Message {
            get {
                return ResourceManager.GetString("ZeroQueueServer.DiscoveryPortConflict.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The &apos;{0}&apos; port must be between 0 and {1}. 的本地化字符串。
        /// </summary>
        internal static string ZeroQueueServer_NamedPortOutOfRange_Message {
            get {
                return ResourceManager.GetString("ZeroQueueServer.NamedPortOutOfRange.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Cannot change the discovery port while the server is running. 的本地化字符串。
        /// </summary>
        internal static string ZeroQueueServer_PortImmutable_Message {
            get {
                return ResourceManager.GetString("ZeroQueueServer.PortImmutable.Message", resourceCulture);
            }
        }

		/// <summary>
		///   查找类似 The '{0}' message header value cannot contain a carriage return or line feed. 的本地化字符串。
		/// </summary>
		internal static string ZeroQueue_HeaderValueInvalid_Message {
			get {
				return ResourceManager.GetString("ZeroQueue.HeaderValueInvalid.Message", resourceCulture);
			}
		}

        /// <summary>
        ///   查找类似 The queue cannot be replaced after the requester has subscribed to a reply topic. 的本地化字符串。
        /// </summary>
        internal static string ZeroRequester_QueueReplacementNotAllowed_Message {
            get {
                return ResourceManager.GetString("ZeroRequester.QueueReplacementNotAllowed.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The &apos;{0}&apos; type of response is not supported. 的本地化字符串。
        /// </summary>
        internal static string ZeroResponse_TypeUnsupported_Message {
            get {
                return ResourceManager.GetString("ZeroResponse.TypeUnsupported.Message", resourceCulture);
            }
        }
    }
}
