//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zongsoft.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zongsoft.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 身份验证失败。 的本地化字符串。
        /// </summary>
        internal static string AuthenticationException_Message {
            get {
                return ResourceManager.GetString("AuthenticationException.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 禁止访问，您没有访问这项资源的授权。 的本地化字符串。
        /// </summary>
        internal static string AuthorizationException_Message {
            get {
                return ResourceManager.GetString("AuthorizationException.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清除当前终端的显示内容。 的本地化字符串。
        /// </summary>
        internal static string ClearCommand_Description {
            get {
                return ResourceManager.GetString("ClearCommand.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清除命令 的本地化字符串。
        /// </summary>
        internal static string ClearCommand_Name {
            get {
                return ResourceManager.GetString("ClearCommand.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 执行失败。 的本地化字符串。
        /// </summary>
        internal static string Command_ExecutionFailed_Message {
            get {
                return ResourceManager.GetString("Command.ExecutionFailed.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 执行成功。 的本地化字符串。
        /// </summary>
        internal static string Command_ExecutionSucceed_Message {
            get {
                return ResourceManager.GetString("Command.ExecutionSucceed.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 超时 的本地化字符串。
        /// </summary>
        internal static string Command_Options_Timeout {
            get {
                return ResourceManager.GetString("Command.Options.Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 命令出错： 的本地化字符串。
        /// </summary>
        internal static string CommandError_Label {
            get {
                return ResourceManager.GetString("CommandError.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定的 &apos;{0}&apos; 命令没有找到。 的本地化字符串。
        /// </summary>
        internal static string CommandNotFound_Message {
            get {
                return ResourceManager.GetString("CommandNotFound.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 应用名称 的本地化字符串。
        /// </summary>
        internal static string ConnectionSettings_Application {
            get {
                return ResourceManager.GetString("ConnectionSettings.Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表示连接的应用标识。 的本地化字符串。
        /// </summary>
        internal static string ConnectionSettings_Application_Description {
            get {
                return ResourceManager.GetString("ConnectionSettings.Application.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字符集 的本地化字符串。
        /// </summary>
        internal static string ConnectionSettings_Charset {
            get {
                return ResourceManager.GetString("ConnectionSettings.Charset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表示字符集的名称，譬如：UTF-8、GBK 等。 的本地化字符串。
        /// </summary>
        internal static string ConnectionSettings_Charset_Description {
            get {
                return ResourceManager.GetString("ConnectionSettings.Charset.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户端名 的本地化字符串。
        /// </summary>
        internal static string ConnectionSettings_Client {
            get {
                return ResourceManager.GetString("ConnectionSettings.Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表示连接程序的客户端名称。 的本地化字符串。
        /// </summary>
        internal static string ConnectionSettings_Client_Description {
            get {
                return ResourceManager.GetString("ConnectionSettings.Client.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据库 的本地化字符串。
        /// </summary>
        internal static string ConnectionSettings_Database {
            get {
                return ResourceManager.GetString("ConnectionSettings.Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表示连接的数据名或标识。 的本地化字符串。
        /// </summary>
        internal static string ConnectionSettings_Database_Description {
            get {
                return ResourceManager.GetString("ConnectionSettings.Database.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编码方案 的本地化字符串。
        /// </summary>
        internal static string ConnectionSettings_Encoding {
            get {
                return ResourceManager.GetString("ConnectionSettings.Encoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表示文本编码方案。 的本地化字符串。
        /// </summary>
        internal static string ConnectionSettings_Encoding_Description {
            get {
                return ResourceManager.GetString("ConnectionSettings.Encoding.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 组别标识 的本地化字符串。
        /// </summary>
        internal static string ConnectionSettings_Group {
            get {
                return ResourceManager.GetString("ConnectionSettings.Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通常表示服务或连接程序所属组别。 的本地化字符串。
        /// </summary>
        internal static string ConnectionSettings_Group_Description {
            get {
                return ResourceManager.GetString("ConnectionSettings.Group.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实例名称 的本地化字符串。
        /// </summary>
        internal static string ConnectionSettings_Instance {
            get {
                return ResourceManager.GetString("ConnectionSettings.Instance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表示连接的实例标识。 的本地化字符串。
        /// </summary>
        internal static string ConnectionSettings_Instance_Description {
            get {
                return ResourceManager.GetString("ConnectionSettings.Instance.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码 的本地化字符串。
        /// </summary>
        internal static string ConnectionSettings_Password {
            get {
                return ResourceManager.GetString("ConnectionSettings.Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表示连接的用户密码。 的本地化字符串。
        /// </summary>
        internal static string ConnectionSettings_Password_Description {
            get {
                return ResourceManager.GetString("ConnectionSettings.Password.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 端口号 的本地化字符串。
        /// </summary>
        internal static string ConnectionSettings_Port {
            get {
                return ResourceManager.GetString("ConnectionSettings.Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表示连接的服务器端口号。 的本地化字符串。
        /// </summary>
        internal static string ConnectionSettings_Port_Description {
            get {
                return ResourceManager.GetString("ConnectionSettings.Port.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提供程序 的本地化字符串。
        /// </summary>
        internal static string ConnectionSettings_Provider {
            get {
                return ResourceManager.GetString("ConnectionSettings.Provider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表示连接提供程序标识。 的本地化字符串。
        /// </summary>
        internal static string ConnectionSettings_Provider_Description {
            get {
                return ResourceManager.GetString("ConnectionSettings.Provider.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务器地址 的本地化字符串。
        /// </summary>
        internal static string ConnectionSettings_Server {
            get {
                return ResourceManager.GetString("ConnectionSettings.Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表示连接的服务器地址。对于多个目标服务器地址，通常采用分号(;)分隔。 的本地化字符串。
        /// </summary>
        internal static string ConnectionSettings_Server_Description {
            get {
                return ResourceManager.GetString("ConnectionSettings.Server.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 超时 的本地化字符串。
        /// </summary>
        internal static string ConnectionSettings_Timeout {
            get {
                return ResourceManager.GetString("ConnectionSettings.Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表示连接超时或相关操作的超时。 的本地化字符串。
        /// </summary>
        internal static string ConnectionSettings_Timeout_Description {
            get {
                return ResourceManager.GetString("ConnectionSettings.Timeout.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名 的本地化字符串。
        /// </summary>
        internal static string ConnectionSettings_UserName {
            get {
                return ResourceManager.GetString("ConnectionSettings.UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表示连接的用户名称。 的本地化字符串。
        /// </summary>
        internal static string ConnectionSettings_UserName_Description {
            get {
                return ResourceManager.GetString("ConnectionSettings.UserName.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 凭证错误：指定的凭证是无效的或已经过期。 的本地化字符串。
        /// </summary>
        internal static string CredentialException_Message {
            get {
                return ResourceManager.GetString("CredentialException.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效的数据参数或者内容值。 的本地化字符串。
        /// </summary>
        internal static string DataArgumentException_Message {
            get {
                return ResourceManager.GetString("DataArgumentException.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据冲突：数据项中 {0} 的 {1} 值重复了。 的本地化字符串。
        /// </summary>
        internal static string DataConflictException_Message {
            get {
                return ResourceManager.GetString("DataConflictException.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据约束失败。 的本地化字符串。
        /// </summary>
        internal static string DataConstraintException_Message {
            get {
                return ResourceManager.GetString("DataConstraintException.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 禁用 的本地化字符串。
        /// </summary>
        internal static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法将“ {0}”处的配置值转换为“ {1}”类型。 的本地化字符串。
        /// </summary>
        internal static string Error_FailedBinding {
            get {
                return ResourceManager.GetString("Error.FailedBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法创建类型为“ {0}”的实例。 的本地化字符串。
        /// </summary>
        internal static string Error_FailedToActivate {
            get {
                return ResourceManager.GetString("Error.FailedToActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 非法的配置属性名“{0}”。位于：{1} 的本地化字符串。
        /// </summary>
        internal static string Error_IllegalConfigurationAttributeName {
            get {
                return ResourceManager.GetString("Error.IllegalConfigurationAttributeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 非法的配置元素的键值“{0}”，键值中不能含有“/”、“\”、“:”、“*”、“?”等字符。位于：{1} 的本地化字符串。
        /// </summary>
        internal static string Error_IllegalConfigurationKeyValue {
            get {
                return ResourceManager.GetString("Error.IllegalConfigurationKeyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发现“{0}”是非法的根节点名称。{1} 的本地化字符串。
        /// </summary>
        internal static string Error_IllegalRootNodeName {
            get {
                return ResourceManager.GetString("Error.IllegalRootNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效的选项配置文件格式，配置元素必须位于&lt;option&gt;元素内。位于：{0} 的本地化字符串。
        /// </summary>
        internal static string Error_InvalidOptionConfigurationFileFormat {
            get {
                return ResourceManager.GetString("Error.InvalidOptionConfigurationFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定的“{0}”是一个无效的未识别属性，未识别属性类型必须是一个键为字符串类型的字典。 的本地化字符串。
        /// </summary>
        internal static string Error_InvalidUnrecognizedProperty {
            get {
                return ResourceManager.GetString("Error.InvalidUnrecognizedProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发现重复的“{0}”键。位于：{1} 的本地化字符串。
        /// </summary>
        internal static string Error_KeyIsDuplicated {
            get {
                return ResourceManager.GetString("Error.KeyIsDuplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持XML名称空间。位于：{0} 的本地化字符串。
        /// </summary>
        internal static string Error_NamespaceIsNotSupported {
            get {
                return ResourceManager.GetString("Error.NamespaceIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 位于“{0}”类型的“{1}”属性不可读。 的本地化字符串。
        /// </summary>
        internal static string Error_PropertyCannotRead {
            get {
                return ResourceManager.GetString("Error.PropertyCannotRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在“{0}”类型中不存在名为“{1}”的属性。 的本地化字符串。
        /// </summary>
        internal static string Error_PropertyNotExists {
            get {
                return ResourceManager.GetString("Error.PropertyNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不能重复操作。 的本地化字符串。
        /// </summary>
        internal static string Error_RepeatedOperation {
            get {
                return ResourceManager.GetString("Error.RepeatedOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法创建类型为“ {0}”的实例，因为不支持多维数组。 的本地化字符串。
        /// </summary>
        internal static string Error_UnsupportedMultidimensionalArray {
            get {
                return ResourceManager.GetString("Error.UnsupportedMultidimensionalArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发现不受支持的节点类型“{0}”。{1} 的本地化字符串。
        /// </summary>
        internal static string Error_UnsupportedNodeType {
            get {
                return ResourceManager.GetString("Error.UnsupportedNodeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发生错误： 的本地化字符串。
        /// </summary>
        internal static string ErrorOccurred_Label {
            get {
                return ResourceManager.GetString("ErrorOccurred.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您确认是否要退出(输入Yes则退出)？ 的本地化字符串。
        /// </summary>
        internal static string ExitCommand_Confirm {
            get {
                return ResourceManager.GetString("ExitCommand.Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出当前应用程序。 的本地化字符串。
        /// </summary>
        internal static string ExitCommand_Description {
            get {
                return ResourceManager.GetString("ExitCommand.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出命令 的本地化字符串。
        /// </summary>
        internal static string ExitCommand_Name {
            get {
                return ResourceManager.GetString("ExitCommand.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 直接退出，不提示确认信息。 的本地化字符串。
        /// </summary>
        internal static string ExitCommand_Options_Confirm {
            get {
                return ResourceManager.GetString("ExitCommand.Options.Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定的 &apos;{0}&apos; 是一个无效的命令选项。 的本地化字符串。
        /// </summary>
        internal static string InvalidCommandOption {
            get {
                return ResourceManager.GetString("InvalidCommandOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定的 &apos;{1}&apos; 是一个无效的 &apos;{0}&apos; 命令选项值。 的本地化字符串。
        /// </summary>
        internal static string InvalidCommandOptionValue {
            get {
                return ResourceManager.GetString("InvalidCommandOptionValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第 {0} 行，第 {1} 列。 的本地化字符串。
        /// </summary>
        internal static string LinePositionInfo {
            get {
                return ResourceManager.GetString("LinePositionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 这是一个侦听消息队列的后台服务程序，它以堵塞方式不断轮询消息队列(即循环以堵塞式调用消息队列的出队方法)，一旦队列中有消息可用则立即将消息出队，然后交给侦听器中的执行器去执行。 的本地化字符串。
        /// </summary>
        internal static string MessageQueueListener_Description {
            get {
                return ResourceManager.GetString("MessageQueueListener.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 消息队列侦听器 的本地化字符串。
        /// </summary>
        internal static string MessageQueueListener_Title {
            get {
                return ResourceManager.GetString("MessageQueueListener.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缺少 &apos;{0}&apos; 命令选项，必须为该选项提供值。 的本地化字符串。
        /// </summary>
        internal static string MissingCommandOption {
            get {
                return ResourceManager.GetString("MissingCommandOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数异常，可能传入了不支持的参数值。 的本地化字符串。
        /// </summary>
        internal static string OperationException_Argument_Message {
            get {
                return ResourceManager.GetString("OperationException.Argument.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未能找到目标，导致操作异常。 的本地化字符串。
        /// </summary>
        internal static string OperationException_Unfound_Message {
            get {
                return ResourceManager.GetString("OperationException.Unfound.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发生未知的操作异常。 的本地化字符串。
        /// </summary>
        internal static string OperationException_Unknown_Message {
            get {
                return ResourceManager.GetString("OperationException.Unknown.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法处理当前操作。 的本地化字符串。
        /// </summary>
        internal static string OperationException_Unprocessed_Message {
            get {
                return ResourceManager.GetString("OperationException.Unprocessed.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未能满足必要的先决条件，导致操作失败。 的本地化字符串。
        /// </summary>
        internal static string OperationException_Unsatisfied_Message {
            get {
                return ResourceManager.GetString("OperationException.Unsatisfied.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持当前操作。 的本地化字符串。
        /// </summary>
        internal static string OperationException_Unsupported_Message {
            get {
                return ResourceManager.GetString("OperationException.Unsupported.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证码生成操作调用太频繁，请等待一会后再来。 的本地化字符串。
        /// </summary>
        internal static string SecretGenerateTooFrequently_Message {
            get {
                return ResourceManager.GetString("SecretGenerateTooFrequently.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帐户已被禁用。 的本地化字符串。
        /// </summary>
        internal static string Security_AccountDisabled_Message {
            get {
                return ResourceManager.GetString("Security.AccountDisabled.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帐户被暂停，可能是因为验证失败次数太多。 的本地化字符串。
        /// </summary>
        internal static string Security_AccountSuspended_Message {
            get {
                return ResourceManager.GetString("Security.AccountSuspended.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帐户尚未通过审核批准。 的本地化字符串。
        /// </summary>
        internal static string Security_AccountUnapproved_Message {
            get {
                return ResourceManager.GetString("Security.AccountUnapproved.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 禁止访问，您的账号没有被授权访问当前资源。 的本地化字符串。
        /// </summary>
        internal static string Security_Forbidden_Message {
            get {
                return ResourceManager.GetString("Security.Forbidden.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效的身份标识。 的本地化字符串。
        /// </summary>
        internal static string Security_InvalidIdentity_Message {
            get {
                return ResourceManager.GetString("Security.InvalidIdentity.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效的密码。 的本地化字符串。
        /// </summary>
        internal static string Security_InvalidPassword_Message {
            get {
                return ResourceManager.GetString("Security.InvalidPassword.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证成功。 的本地化字符串。
        /// </summary>
        internal static string Security_Succeed_Message {
            get {
                return ResourceManager.GetString("Security.Succeed.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 其他未知的安全原因。 的本地化字符串。
        /// </summary>
        internal static string Security_Unknown_Message {
            get {
                return ResourceManager.GetString("Security.Unknown.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通过系统Shell来执行外部命令。 的本地化字符串。
        /// </summary>
        internal static string ShellCommand_Description {
            get {
                return ResourceManager.GetString("ShellCommand.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 外部命令执行器 的本地化字符串。
        /// </summary>
        internal static string ShellCommand_Name {
            get {
                return ResourceManager.GetString("ShellCommand.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运行外部命令的超时，单位：毫秒。 的本地化字符串。
        /// </summary>
        internal static string ShellCommand_Options_Timeout {
            get {
                return ResourceManager.GetString("ShellCommand.Options.Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示：按 Ctrl+C 组合键可以退出侦听模式。 的本地化字符串。
        /// </summary>
        internal static string WorkerListenCommand_Prompt {
            get {
                return ResourceManager.GetString("WorkerListenCommand.Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 欢迎进入 {0} 的侦听模式。 的本地化字符串。
        /// </summary>
        internal static string WorkerListenCommand_Welcome {
            get {
                return ResourceManager.GetString("WorkerListenCommand.Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 暂停 的本地化字符串。
        /// </summary>
        internal static string WorkerPauseCommand_Name {
            get {
                return ResourceManager.GetString("WorkerPauseCommand.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 恢复 的本地化字符串。
        /// </summary>
        internal static string WorkerResumeCommand_Name {
            get {
                return ResourceManager.GetString("WorkerResumeCommand.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动 的本地化字符串。
        /// </summary>
        internal static string WorkerStartCommand_Name {
            get {
                return ResourceManager.GetString("WorkerStartCommand.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 强制启动，即使命令被禁用也尝试启动。 的本地化字符串。
        /// </summary>
        internal static string WorkerStartCommand_Options_Force {
            get {
                return ResourceManager.GetString("WorkerStartCommand.Options.Force", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已暂停 的本地化字符串。
        /// </summary>
        internal static string WorkerState_Paused {
            get {
                return ResourceManager.GetString("WorkerState.Paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 暂停中 的本地化字符串。
        /// </summary>
        internal static string WorkerState_Pausing {
            get {
                return ResourceManager.GetString("WorkerState.Pausing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 恢复中 的本地化字符串。
        /// </summary>
        internal static string WorkerState_Resuming {
            get {
                return ResourceManager.GetString("WorkerState.Resuming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运行中 的本地化字符串。
        /// </summary>
        internal static string WorkerState_Running {
            get {
                return ResourceManager.GetString("WorkerState.Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动中 的本地化字符串。
        /// </summary>
        internal static string WorkerState_Starting {
            get {
                return ResourceManager.GetString("WorkerState.Starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已停止 的本地化字符串。
        /// </summary>
        internal static string WorkerState_Stopped {
            get {
                return ResourceManager.GetString("WorkerState.Stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止中 的本地化字符串。
        /// </summary>
        internal static string WorkerState_Stopping {
            get {
                return ResourceManager.GetString("WorkerState.Stopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止 的本地化字符串。
        /// </summary>
        internal static string WorkerStopCommand_Name {
            get {
                return ResourceManager.GetString("WorkerStopCommand.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色 的本地化字符串。
        /// </summary>
        internal static string Zongsoft_Security_Privileges_MemberType_Role {
            get {
                return ResourceManager.GetString("Zongsoft.Security.Privileges.MemberType.Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户 的本地化字符串。
        /// </summary>
        internal static string Zongsoft_Security_Privileges_MemberType_User {
            get {
                return ResourceManager.GetString("Zongsoft.Security.Privileges.MemberType.User", resourceCulture);
            }
        }
    }
}
