//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zongsoft.Properties {
    using System;


    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zongsoft.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   查找类似 The cache of authentication failover does not support the increment(ISequence) operation. 的本地化字符串。
        /// </summary>
        internal static string Attempter_SequenceNotSupported_Message {
            get {
                return ResourceManager.GetString("Attempter.SequenceNotSupported.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Invalid authenticator scheme. 的本地化字符串。
        /// </summary>
        internal static string Authentication_InvalidScheme_Message {
            get {
                return ResourceManager.GetString("Authentication.InvalidScheme.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Missing the required credential provider. 的本地化字符串。
        /// </summary>
        internal static string Authentication_MissingAuthority_Message {
            get {
                return ResourceManager.GetString("Authentication.MissingAuthority.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Missing identity. 的本地化字符串。
        /// </summary>
        internal static string Authentication_MissingIdentity_Message {
            get {
                return ResourceManager.GetString("Authentication.MissingIdentity.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Missing the required authentication token. 的本地化字符串。
        /// </summary>
        internal static string Authentication_MissingToken_Message {
            get {
                return ResourceManager.GetString("Authentication.MissingToken.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Authentication failed. 的本地化字符串。
        /// </summary>
        internal static string AuthenticationException_Message {
            get {
                return ResourceManager.GetString("AuthenticationException.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Access denied: You do not have permission to access this resource. 的本地化字符串。
        /// </summary>
        internal static string AuthorizationException_Message {
            get {
                return ResourceManager.GetString("AuthorizationException.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The notification queue capacity must be positive. 的本地化字符串。
        /// </summary>
        internal static string CacheSubscription_InvalidCapacity_Message {
            get {
                return ResourceManager.GetString("CacheSubscription.InvalidCapacity.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The notification kinds must contain only defined flags and cannot be None. 的本地化字符串。
        /// </summary>
        internal static string CacheSubscription_InvalidKind_Message {
            get {
                return ResourceManager.GetString("CacheSubscription.InvalidKind.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Invalid checksum text format. 的本地化字符串。
        /// </summary>
        internal static string Checksum_InvalidFormat_Message {
            get {
                return ResourceManager.GetString("Checksum.InvalidFormat.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Clear the display contents of the current terminal. 的本地化字符串。
        /// </summary>
        internal static string ClearCommand_Description {
            get {
                return ResourceManager.GetString("ClearCommand.Description", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Clear command 的本地化字符串。
        /// </summary>
        internal static string ClearCommand_Name {
            get {
                return ResourceManager.GetString("ClearCommand.Name", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 {0} Execution failed. 的本地化字符串。
        /// </summary>
        internal static string Command_ExecutionFailed_Message {
            get {
                return ResourceManager.GetString("Command.ExecutionFailed.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 {0} Execution successful. 的本地化字符串。
        /// </summary>
        internal static string Command_ExecutionSucceed_Message {
            get {
                return ResourceManager.GetString("Command.ExecutionSucceed.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The specified command name contains illegal characters. 的本地化字符串。
        /// </summary>
        internal static string Command_InvalidName_Message {
            get {
                return ResourceManager.GetString("Command.InvalidName.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Timeout 的本地化字符串。
        /// </summary>
        internal static string Command_Options_Timeout {
            get {
                return ResourceManager.GetString("Command.Options.Timeout", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The specified alias contains illegal characters. 的本地化字符串。
        /// </summary>
        internal static string CommandAlias_InvalidCharacters_Message {
            get {
                return ResourceManager.GetString("CommandAlias.InvalidCharacters.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Command error:  的本地化字符串。
        /// </summary>
        internal static string CommandError_Label {
            get {
                return ResourceManager.GetString("CommandError.Label", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Missing executable commands. 的本地化字符串。
        /// </summary>
        internal static string CommandExecutor_MissingCommand_Message {
            get {
                return ResourceManager.GetString("CommandExecutor.MissingCommand.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The specified &apos;{0}&apos; command was not found. 的本地化字符串。
        /// </summary>
        internal static string CommandNotFound_Message {
            get {
                return ResourceManager.GetString("CommandNotFound.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The specified &apos;{0}&apos; handler does not match. 的本地化字符串。
        /// </summary>
        internal static string Communication_ListenerHandlerMismatch_Message {
            get {
                return ResourceManager.GetString("Communication.ListenerHandlerMismatch.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Missing the required packetizer for the receive operation. 的本地化字符串。
        /// </summary>
        internal static string Communication_ListenerPacketizerRequired_Message {
            get {
                return ResourceManager.GetString("Communication.ListenerPacketizerRequired.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The specified &apos;{0}&apos; message compression algorithm is not supported. 的本地化字符串。
        /// </summary>
        internal static string Compressor_Undefined_Message {
            get {
                return ResourceManager.GetString("Compressor.Undefined.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Application name 的本地化字符串。
        /// </summary>
        internal static string ConnectionSettings_Application {
            get {
                return ResourceManager.GetString("ConnectionSettings.Application", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Indicates the application identifier for the connection. 的本地化字符串。
        /// </summary>
        internal static string ConnectionSettings_Application_Description {
            get {
                return ResourceManager.GetString("ConnectionSettings.Application.Description", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Character set 的本地化字符串。
        /// </summary>
        internal static string ConnectionSettings_Charset {
            get {
                return ResourceManager.GetString("ConnectionSettings.Charset", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Indicates the name of the character set, such as UTF-8, GBK, etc. 的本地化字符串。
        /// </summary>
        internal static string ConnectionSettings_Charset_Description {
            get {
                return ResourceManager.GetString("ConnectionSettings.Charset.Description", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Client name 的本地化字符串。
        /// </summary>
        internal static string ConnectionSettings_Client {
            get {
                return ResourceManager.GetString("ConnectionSettings.Client", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Indicates the client name of the connection program. 的本地化字符串。
        /// </summary>
        internal static string ConnectionSettings_Client_Description {
            get {
                return ResourceManager.GetString("ConnectionSettings.Client.Description", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Database 的本地化字符串。
        /// </summary>
        internal static string ConnectionSettings_Database {
            get {
                return ResourceManager.GetString("ConnectionSettings.Database", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Indicates the name or identifier of the database to connect to. 的本地化字符串。
        /// </summary>
        internal static string ConnectionSettings_Database_Description {
            get {
                return ResourceManager.GetString("ConnectionSettings.Database.Description", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Encoding scheme 的本地化字符串。
        /// </summary>
        internal static string ConnectionSettings_Encoding {
            get {
                return ResourceManager.GetString("ConnectionSettings.Encoding", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Indicates the text encoding scheme. 的本地化字符串。
        /// </summary>
        internal static string ConnectionSettings_Encoding_Description {
            get {
                return ResourceManager.GetString("ConnectionSettings.Encoding.Description", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Group identifier 的本地化字符串。
        /// </summary>
        internal static string ConnectionSettings_Group {
            get {
                return ResourceManager.GetString("ConnectionSettings.Group", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Usually indicates the group to which a service or connection program belongs. 的本地化字符串。
        /// </summary>
        internal static string ConnectionSettings_Group_Description {
            get {
                return ResourceManager.GetString("ConnectionSettings.Group.Description", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Instance name 的本地化字符串。
        /// </summary>
        internal static string ConnectionSettings_Instance {
            get {
                return ResourceManager.GetString("ConnectionSettings.Instance", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Indicates the connection instance identifier. 的本地化字符串。
        /// </summary>
        internal static string ConnectionSettings_Instance_Description {
            get {
                return ResourceManager.GetString("ConnectionSettings.Instance.Description", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Password 的本地化字符串。
        /// </summary>
        internal static string ConnectionSettings_Password {
            get {
                return ResourceManager.GetString("ConnectionSettings.Password", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Indicates the password of the connected user. 的本地化字符串。
        /// </summary>
        internal static string ConnectionSettings_Password_Description {
            get {
                return ResourceManager.GetString("ConnectionSettings.Password.Description", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Port number 的本地化字符串。
        /// </summary>
        internal static string ConnectionSettings_Port {
            get {
                return ResourceManager.GetString("ConnectionSettings.Port", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Indicates the server port number for the connection. 的本地化字符串。
        /// </summary>
        internal static string ConnectionSettings_Port_Description {
            get {
                return ResourceManager.GetString("ConnectionSettings.Port.Description", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Provider 的本地化字符串。
        /// </summary>
        internal static string ConnectionSettings_Provider {
            get {
                return ResourceManager.GetString("ConnectionSettings.Provider", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Indicates the connection provider identifier. 的本地化字符串。
        /// </summary>
        internal static string ConnectionSettings_Provider_Description {
            get {
                return ResourceManager.GetString("ConnectionSettings.Provider.Description", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Server address 的本地化字符串。
        /// </summary>
        internal static string ConnectionSettings_Server {
            get {
                return ResourceManager.GetString("ConnectionSettings.Server", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Indicates the server address to connect to. For multiple target server addresses, they are typically separated by semicolons (;). 的本地化字符串。
        /// </summary>
        internal static string ConnectionSettings_Server_Description {
            get {
                return ResourceManager.GetString("ConnectionSettings.Server.Description", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Timeout 的本地化字符串。
        /// </summary>
        internal static string ConnectionSettings_Timeout {
            get {
                return ResourceManager.GetString("ConnectionSettings.Timeout", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Indicates a connection timeout or a timeout for a related operation. 的本地化字符串。
        /// </summary>
        internal static string ConnectionSettings_Timeout_Description {
            get {
                return ResourceManager.GetString("ConnectionSettings.Timeout.Description", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 User name 的本地化字符串。
        /// </summary>
        internal static string ConnectionSettings_UserName {
            get {
                return ResourceManager.GetString("ConnectionSettings.UserName", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Indicates the user name of the connection. 的本地化字符串。
        /// </summary>
        internal static string ConnectionSettings_UserName_Description {
            get {
                return ResourceManager.GetString("ConnectionSettings.UserName.Description", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Missing database connection settings. 的本地化字符串。
        /// </summary>
        internal static string DataAccess_MissingConnections_Message {
            get {
                return ResourceManager.GetString("DataAccess.MissingConnections.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Missing required Sequence service. 的本地化字符串。
        /// </summary>
        internal static string DataAccess_MissingSequence_Message {
            get {
                return ResourceManager.GetString("DataAccess.MissingSequence.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Invalid data parameters or values. 的本地化字符串。
        /// </summary>
        internal static string DataArgumentException_Message {
            get {
                return ResourceManager.GetString("DataArgumentException.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Data conflict: The value of {1} in data {0} is duplicated. 的本地化字符串。
        /// </summary>
        internal static string DataConflictException_Message {
            get {
                return ResourceManager.GetString("DataConflictException.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Data constraint failure. 的本地化字符串。
        /// </summary>
        internal static string DataConstraintException_Message {
            get {
                return ResourceManager.GetString("DataConstraintException.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The entity property cannot be added or updated to the properties because the entity to which this property belongs cannot be set. 的本地化字符串。
        /// </summary>
        internal static string DataEntityProperty_OwnerReadOnly_Message {
            get {
                return ResourceManager.GetString("DataEntityProperty.OwnerReadOnly.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Missing specified search member definitions. 的本地化字符串。
        /// </summary>
        internal static string DataSearcher_MissingMembers_Message {
            get {
                return ResourceManager.GetString("DataSearcher.MissingMembers.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Missing the required keyword condition resolver. 的本地化字符串。
        /// </summary>
        internal static string DataSearcher_MissingResolver_Message {
            get {
                return ResourceManager.GetString("DataSearcher.MissingResolver.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The criteria cann&apos;t is null on delete operation. 的本地化字符串。
        /// </summary>
        internal static string DataService_DeleteRequiresCriteria_Message {
            get {
                return ResourceManager.GetString("DataService.DeleteRequiresCriteria.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The {0} operation is not allowed. 的本地化字符串。
        /// </summary>
        internal static string DataService_OperationNotAllowed_Message {
            get {
                return ResourceManager.GetString("DataService.OperationNotAllowed.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Illegal format parameter value. 的本地化字符串。
        /// </summary>
        internal static string DataServiceMutability_InvalidFormat_Message {
            get {
                return ResourceManager.GetString("DataServiceMutability.InvalidFormat.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Disabled 的本地化字符串。
        /// </summary>
        internal static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The distributed lock has been released. 的本地化字符串。
        /// </summary>
        internal static string DistributedLock_Released_Message {
            get {
                return ResourceManager.GetString("DistributedLock.Released.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The iterator has terminated. 的本地化字符串。
        /// </summary>
        internal static string Enumerable_Completed_Message {
            get {
                return ResourceManager.GetString("Enumerable.Completed.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Sequence contains no elements. 的本地化字符串。
        /// </summary>
        internal static string Enumerable_Empty_Message {
            get {
                return ResourceManager.GetString("Enumerable.Empty.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The iterator has not yet started, please call the MoveNext() method first. 的本地化字符串。
        /// </summary>
        internal static string Enumerable_NotStarted_Message {
            get {
                return ResourceManager.GetString("Enumerable.NotStarted.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The configuration value at &quot;{0}&quot; cannot be converted to type &quot;{1}&quot;. 的本地化字符串。
        /// </summary>
        internal static string Error_FailedBinding_Message {
            get {
                return ResourceManager.GetString("Error.FailedBinding.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Unable to create an instance of type &quot;{0}&quot;. 的本地化字符串。
        /// </summary>
        internal static string Error_FailedToActivate_Message {
            get {
                return ResourceManager.GetString("Error.FailedToActivate.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The configuration property name &quot;{0}&quot; is invalid. Located at: {1} 的本地化字符串。
        /// </summary>
        internal static string Error_IllegalConfigurationAttributeName_Message {
            get {
                return ResourceManager.GetString("Error.IllegalConfigurationAttributeName.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The value &quot;{0}&quot; of the illegal configuration element cannot contain characters such as &apos;/&apos;, &apos;\&apos;, &apos;:&apos;, &apos;*&apos;, or &apos;?&apos;. Located at: {1} 的本地化字符串。
        /// </summary>
        internal static string Error_IllegalConfigurationKeyValue_Message {
            get {
                return ResourceManager.GetString("Error.IllegalConfigurationKeyValue.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The root node name &quot;{0}&quot; is invalid. {1} 的本地化字符串。
        /// </summary>
        internal static string Error_IllegalRootNodeName_Message {
            get {
                return ResourceManager.GetString("Error.IllegalRootNodeName.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Invalid option configuration file format. The configuration elements must be located within the &lt;option&gt; element. Located at: {0} 的本地化字符串。
        /// </summary>
        internal static string Error_InvalidOptionConfigurationFileFormat_Message {
            get {
                return ResourceManager.GetString("Error.InvalidOptionConfigurationFileFormat.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The specified &quot;{0}&quot; is an invalid unrecognized property. The type of unrecognized properties must be a dictionary with string keys. 的本地化字符串。
        /// </summary>
        internal static string Error_InvalidUnrecognizedProperty_Message {
            get {
                return ResourceManager.GetString("Error.InvalidUnrecognizedProperty.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Duplicate &quot;{0}&quot; key found. Located at: {1} 的本地化字符串。
        /// </summary>
        internal static string Error_KeyIsDuplicated_Message {
            get {
                return ResourceManager.GetString("Error.KeyIsDuplicated.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 XML namespaces are not supported. Located at: {0} 的本地化字符串。
        /// </summary>
        internal static string Error_NamespaceIsNotSupported_Message {
            get {
                return ResourceManager.GetString("Error.NamespaceIsNotSupported.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The &quot;{1}&quot; property of type &quot;{0}&quot; is not readable. 的本地化字符串。
        /// </summary>
        internal static string Error_PropertyCannotRead_Message {
            get {
                return ResourceManager.GetString("Error.PropertyCannotRead.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 There is no property named &quot;{1}&quot; in the &quot;{0}&quot; type. 的本地化字符串。
        /// </summary>
        internal static string Error_PropertyNotExists_Message {
            get {
                return ResourceManager.GetString("Error.PropertyNotExists.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Unable to create an instance of type &quot;{0}&quot; because multidimensional arrays are not supported. 的本地化字符串。
        /// </summary>
        internal static string Error_UnsupportedMultidimensionalArray_Message {
            get {
                return ResourceManager.GetString("Error.UnsupportedMultidimensionalArray.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Unsupported node type &quot;{0}&quot; detected. {1} 的本地化字符串。
        /// </summary>
        internal static string Error_UnsupportedNodeType_Message {
            get {
                return ResourceManager.GetString("Error.UnsupportedNodeType.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Error occurred:  的本地化字符串。
        /// </summary>
        internal static string ErrorOccurred_Label {
            get {
                return ResourceManager.GetString("ErrorOccurred.Label", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 An error occurred. 的本地化字符串。
        /// </summary>
        internal static string ErrorOccurred_Message {
            get {
                return ResourceManager.GetString("ErrorOccurred.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The bound event argument type do not match. 的本地化字符串。
        /// </summary>
        internal static string EventBinder_ArgumentTypeMismatch_Message {
            get {
                return ResourceManager.GetString("EventBinder.ArgumentTypeMismatch.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Do you want to quit? (Enter yes to quit) 的本地化字符串。
        /// </summary>
        internal static string ExitCommand_Confirm {
            get {
                return ResourceManager.GetString("ExitCommand.Confirm", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Exit the current application. 的本地化字符串。
        /// </summary>
        internal static string ExitCommand_Description {
            get {
                return ResourceManager.GetString("ExitCommand.Description", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Exit command 的本地化字符串。
        /// </summary>
        internal static string ExitCommand_Name {
            get {
                return ResourceManager.GetString("ExitCommand.Name", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Exit directly without prompting for confirmation. 的本地化字符串。
        /// </summary>
        internal static string ExitCommand_Options_Confirm {
            get {
                return ResourceManager.GetString("ExitCommand.Options.Confirm", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The &apos;{0}&apos; property is required. 的本地化字符串。
        /// </summary>
        internal static string Hardware_RequiredProperty_Message {
            get {
                return ResourceManager.GetString("Hardware.RequiredProperty.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The name contains illegal character(s). 的本地化字符串。
        /// </summary>
        internal static string HierarchicalNode_InvalidName_Message {
            get {
                return ResourceManager.GetString("HierarchicalNode.InvalidName.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The root node cannot be added to the child nodes. 的本地化字符串。
        /// </summary>
        internal static string HierarchicalNode_RootAsChild_Message {
            get {
                return ResourceManager.GetString("HierarchicalNode.RootAsChild.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Invalid format of the identifier. 的本地化字符串。
        /// </summary>
        internal static string Identifier_InvalidFormat_Message {
            get {
                return ResourceManager.GetString("Identifier.InvalidFormat.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The specified &apos;{0}&apos; is an invalid command option. 的本地化字符串。
        /// </summary>
        internal static string InvalidCommandOption_Message {
            get {
                return ResourceManager.GetString("InvalidCommandOption.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The specified &apos;{1}&apos; is an invalid &apos;{0}&apos; command option value. 的本地化字符串。
        /// </summary>
        internal static string InvalidCommandOptionValue_Message {
            get {
                return ResourceManager.GetString("InvalidCommandOptionValue.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Invalid format. 的本地化字符串。
        /// </summary>
        internal static string InvalidFormat_Message {
            get {
                return ResourceManager.GetString("InvalidFormat.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Row {0}, column {1}. 的本地化字符串。
        /// </summary>
        internal static string LinePositionInfo {
            get {
                return ResourceManager.GetString("LinePositionInfo", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The lock acquisition is no longer active. 的本地化字符串。
        /// </summary>
        internal static string Locker_AcquisitionInactive_Message {
            get {
                return ResourceManager.GetString("Locker.AcquisitionInactive.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Invalid member expression. 的本地化字符串。
        /// </summary>
        internal static string MemberExpression_Invalid_Message {
            get {
                return ResourceManager.GetString("MemberExpression.Invalid.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 An unknown error occurred in the parser. 的本地化字符串。
        /// </summary>
        internal static string MemberExpression_UnknownError_Message {
            get {
                return ResourceManager.GetString("MemberExpression.UnknownError.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The current memory cache options is immutable. 的本地化字符串。
        /// </summary>
        internal static string MemoryCache_ImmutableOptions_Message {
            get {
                return ResourceManager.GetString("MemoryCache.ImmutableOptions.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The specified {0} message queue connection setting named &apos;{1}&apos; was not found. 的本地化字符串。
        /// </summary>
        internal static string Messaging_ConnectionSettingsNotFound_Message {
            get {
                return ResourceManager.GetString("Messaging.ConnectionSettingsNotFound.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The specified &apos;{0}&apos; connection setting is not of the required &apos;{1}&apos; settings type. 的本地化字符串。
        /// </summary>
        internal static string Messaging_ConnectionSettingsTypeMismatch_Message {
            get {
                return ResourceManager.GetString("Messaging.ConnectionSettingsTypeMismatch.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The &apos;{0}&apos; feature is not supported by the &apos;{1}&apos; message queue. 的本地化字符串。
        /// </summary>
        internal static string Messaging_FeatureNotSupported_Message {
            get {
                return ResourceManager.GetString("Messaging.FeatureNotSupported.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The message queue guarder named &apos;{0}&apos; cannot be started because its &apos;{1}&apos; property is null. 的本地化字符串。
        /// </summary>
        internal static string Messaging_GuarderQueueMissing_Warning {
            get {
                return ResourceManager.GetString("Messaging.GuarderQueueMissing.Warning", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 {0}: The specified &apos;{1}&apos; message queue is not defined. 的本地化字符串。
        /// </summary>
        internal static string Messaging_QueueUndefined_Message {
            get {
                return ResourceManager.GetString("Messaging.QueueUndefined.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The &apos;{0}&apos; message reliability is not supported by the &apos;{1}&apos; message queue. 的本地化字符串。
        /// </summary>
        internal static string Messaging_ReliabilityNotSupported_Message {
            get {
                return ResourceManager.GetString("Messaging.ReliabilityNotSupported.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The message storage factory failed to create storage for the &apos;{0}&apos; broker. 的本地化字符串。
        /// </summary>
        internal static string Messaging_StorageCreationFailed_Message {
            get {
                return ResourceManager.GetString("Messaging.StorageCreationFailed.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The existing subscription for the &apos;{0}&apos; topic has a different handler, tags, or options. 的本地化字符串。
        /// </summary>
        internal static string Messaging_SubscriptionConflict_Message {
            get {
                return ResourceManager.GetString("Messaging.SubscriptionConflict.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The command option &apos;{0}&apos; is missing. A value must be provided for this option. 的本地化字符串。
        /// </summary>
        internal static string MissingCommandOption_Message {
            get {
                return ResourceManager.GetString("MissingCommandOption.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Illegal long integer suffix symbol(L), because it&apos;s a float numeric literal. 的本地化字符串。
        /// </summary>
        internal static string NumberTokenizer_InvalidLongSuffix_Message {
            get {
                return ResourceManager.GetString("NumberTokenizer.InvalidLongSuffix.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Illegal numeric literal, it contains multiple dot(.) symbol. 的本地化字符串。
        /// </summary>
        internal static string NumberTokenizer_MultipleDots_Message {
            get {
                return ResourceManager.GetString("NumberTokenizer.MultipleDots.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Illegal numeric literal, cann&apos;t end with a dot(.) symbol. 的本地化字符串。
        /// </summary>
        internal static string NumberTokenizer_TrailingDot_Message {
            get {
                return ResourceManager.GetString("NumberTokenizer.TrailingDot.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Argument exception, possibly an unsupported argument value was passed. 的本地化字符串。
        /// </summary>
        internal static string OperationException_Argument_Message {
            get {
                return ResourceManager.GetString("OperationException.Argument.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The target could not be found, resulting in operation failure. 的本地化字符串。
        /// </summary>
        internal static string OperationException_Unfound_Message {
            get {
                return ResourceManager.GetString("OperationException.Unfound.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 An unknown operation error has occurred. 的本地化字符串。
        /// </summary>
        internal static string OperationException_Unknown_Message {
            get {
                return ResourceManager.GetString("OperationException.Unknown.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Unable to process the current operation. 的本地化字符串。
        /// </summary>
        internal static string OperationException_Unprocessed_Message {
            get {
                return ResourceManager.GetString("OperationException.Unprocessed.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Failure to meet the necessary prerequisites resulted in the operation failing. 的本地化字符串。
        /// </summary>
        internal static string OperationException_Unsatisfied_Message {
            get {
                return ResourceManager.GetString("OperationException.Unsatisfied.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The current operation is not supported. 的本地化字符串。
        /// </summary>
        internal static string OperationException_Unsupported_Message {
            get {
                return ResourceManager.GetString("OperationException.Unsupported.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Illegal paging format. 的本地化字符串。
        /// </summary>
        internal static string Paging_InvalidFormat_Message {
            get {
                return ResourceManager.GetString("Paging.InvalidFormat.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The specified parameter value is null, but the declared type is not the Nullable type. 的本地化字符串。
        /// </summary>
        internal static string Parameters_NullForNonNullable_Message {
            get {
                return ResourceManager.GetString("Parameters.NullForNonNullable.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The length of nonce is too long. 的本地化字符串。
        /// </summary>
        internal static string Password_NonceTooLong_Message {
            get {
                return ResourceManager.GetString("Password.NonceTooLong.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The length of nonce is too short(must be greater than or equal to 4). 的本地化字符串。
        /// </summary>
        internal static string Password_NonceTooShort_Message {
            get {
                return ResourceManager.GetString("Password.NonceTooShort.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The path separator must be followed by the path anchor. 的本地化字符串。
        /// </summary>
        internal static string Path_AnchorRequired_Message {
            get {
                return ResourceManager.GetString("Path.AnchorRequired.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Invalid path anchor. 的本地化字符串。
        /// </summary>
        internal static string Path_InvalidAnchor_Message {
            get {
                return ResourceManager.GetString("Path.InvalidAnchor.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Invalid path, it contains a illegal character. 的本地化字符串。
        /// </summary>
        internal static string Path_InvalidCharacter_Message {
            get {
                return ResourceManager.GetString("Path.InvalidCharacter.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The first character must be a letter, number or underscore. 的本地化字符串。
        /// </summary>
        internal static string Path_InvalidFirstCharacter_Message {
            get {
                return ResourceManager.GetString("Path.InvalidFirstCharacter.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 This profile is already being saved. 的本地化字符串。
        /// </summary>
        internal static string Profiles_AlreadySaving_Message {
            get {
                return ResourceManager.GetString("Profiles.AlreadySaving.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Profile blank line positions must be nonnegative and increasing. 的本地化字符串。
        /// </summary>
        internal static string Profiles_BlanksInvalid_Message {
            get {
                return ResourceManager.GetString("Profiles.BlanksInvalid.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Circular profile import: {0}. Referenced from {1}, line {2}. 的本地化字符串。
        /// </summary>
        internal static string Profiles_CircularImport_Message {
            get {
                return ResourceManager.GetString("Profiles.CircularImport.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The comment cannot be represented consistently as a profile declaration. 的本地化字符串。
        /// </summary>
        internal static string Profiles_CommentInvalid_Message {
            get {
                return ResourceManager.GetString("Profiles.CommentInvalid.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 An entry named &apos;{0}&apos; is already declared in this profile. 的本地化字符串。
        /// </summary>
        internal static string Profiles_EntryDuplicate_Message {
            get {
                return ResourceManager.GetString("Profiles.EntryDuplicate.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The entry &apos;{0}&apos; cannot be represented in a profile. 的本地化字符串。
        /// </summary>
        internal static string Profiles_EntryInvalid_Message {
            get {
                return ResourceManager.GetString("Profiles.EntryInvalid.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Unable to resolve the profile path link: {0}. 的本地化字符串。
        /// </summary>
        internal static string Profiles_LinkResolutionFailed_Message {
            get {
                return ResourceManager.GetString("Profiles.LinkResolutionFailed.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Maximum profile import depth exceeded: {0}. Referenced from {1}, line {2}. 的本地化字符串。
        /// </summary>
        internal static string Profiles_MaximumDepth_Message {
            get {
                return ResourceManager.GetString("Profiles.MaximumDepth.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The profile file is read-only: &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string Profiles_ReadOnly_Message {
            get {
                return ResourceManager.GetString("Profiles.ReadOnly.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Relative import &quot;{0}&quot; requires a source file path (line {1}). 的本地化字符串。
        /// </summary>
        internal static string Profiles_RelativeImportRequiresFile_Message {
            get {
                return ResourceManager.GetString("Profiles.RelativeImportRequiresFile.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Conflicting modified profiles target the same file: &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string Profiles_SaveConflict_Message {
            get {
                return ResourceManager.GetString("Profiles.SaveConflict.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Failed to save &apos;{0}&apos;. Completed files: {1}. 的本地化字符串。
        /// </summary>
        internal static string Profiles_SaveFailed_Message {
            get {
                return ResourceManager.GetString("Profiles.SaveFailed.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Profiles must not be modified during saving. 的本地化字符串。
        /// </summary>
        internal static string Profiles_SaveMutation_Message {
            get {
                return ResourceManager.GetString("Profiles.SaveMutation.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 A section with the same name already exists. 的本地化字符串。
        /// </summary>
        internal static string Profiles_SectionDuplicate_Message {
            get {
                return ResourceManager.GetString("Profiles.SectionDuplicate.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The section name cannot be represented in a profile: &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string Profiles_SectionInvalid_Message {
            get {
                return ResourceManager.GetString("Profiles.SectionInvalid.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Edit the declaration through its source profile and section. 的本地化字符串。
        /// </summary>
        internal static string Profiles_SourceEdit_Message {
            get {
                return ResourceManager.GetString("Profiles.SourceEdit.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The modified profile has no source file path. 的本地化字符串。
        /// </summary>
        internal static string Profiles_SourceRequired_Message {
            get {
                return ResourceManager.GetString("Profiles.SourceRequired.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Invalid datetime range expression format. 的本地化字符串。
        /// </summary>
        internal static string RangeParser_InvalidDateTimeFormat_Message {
            get {
                return ResourceManager.GetString("RangeParser.InvalidDateTimeFormat.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The {0} range function is missing required parameters. 的本地化字符串。
        /// </summary>
        internal static string RangeParser_MissingArguments_Message {
            get {
                return ResourceManager.GetString("RangeParser.MissingArguments.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Missing the closing parenthesis. 的本地化字符串。
        /// </summary>
        internal static string RangeParser_MissingClosingParenthesis_Message {
            get {
                return ResourceManager.GetString("RangeParser.MissingClosingParenthesis.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The argument in the datetime range expression must be a number. 的本地化字符串。
        /// </summary>
        internal static string RangeParser_NumericArgumentRequired_Message {
            get {
                return ResourceManager.GetString("RangeParser.NumericArgumentRequired.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The range expression contains redundant content. 的本地化字符串。
        /// </summary>
        internal static string RangeParser_RedundantContent_Message {
            get {
                return ResourceManager.GetString("RangeParser.RedundantContent.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The {0} range function has too many parameters. 的本地化字符串。
        /// </summary>
        internal static string RangeParser_TooManyArguments_Message {
            get {
                return ResourceManager.GetString("RangeParser.TooManyArguments.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 ParsingError: The parsing stack is empty. 的本地化字符串。
        /// </summary>
        internal static string Schema_EmptyParsingStack_Message {
            get {
                return ResourceManager.GetString("Schema.EmptyParsingStack.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 {0} (at position {1}). 的本地化字符串。
        /// </summary>
        internal static string Schema_ErrorPosition_Message {
            get {
                return ResourceManager.GetString("Schema.ErrorPosition.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 SyntaxError: The identifier of the data schema contains whitespace characters. 的本地化字符串。
        /// </summary>
        internal static string Schema_IdentifierContainsWhitespace_Message {
            get {
                return ResourceManager.GetString("Schema.IdentifierContainsWhitespace.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 SyntaxError: The identifier of the data schema contains &apos;{0}&apos; illegal character. 的本地化字符串。
        /// </summary>
        internal static string Schema_IdentifierIllegalCharacter_Message {
            get {
                return ResourceManager.GetString("Schema.IdentifierIllegalCharacter.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 SyntaxError: The identifier of the data schema cannot start with a digit. 的本地化字符串。
        /// </summary>
        internal static string Schema_IdentifierStartsWithDigit_Message {
            get {
                return ResourceManager.GetString("Schema.IdentifierStartsWithDigit.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 SyntaxError: Contains the illegal character &apos;{0}&apos; in the data schema. 的本地化字符串。
        /// </summary>
        internal static string Schema_IllegalCharacter_Message {
            get {
                return ResourceManager.GetString("Schema.IllegalCharacter.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 SyntaxError: Contains the illegal character &apos;{0}&apos; after sorting in the data schema. 的本地化字符串。
        /// </summary>
        internal static string Schema_IllegalCharacterAfterSorting_Message {
            get {
                return ResourceManager.GetString("Schema.IllegalCharacterAfterSorting.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 SyntaxError: The data schema expression is incorrect({0}). 的本地化字符串。
        /// </summary>
        internal static string Schema_IncorrectExpression_Message {
            get {
                return ResourceManager.GetString("Schema.IncorrectExpression.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 SyntaxError: The exclusion wildcard of the data schema is invalid. 的本地化字符串。
        /// </summary>
        internal static string Schema_InvalidExclusionWildcard_Message {
            get {
                return ResourceManager.GetString("Schema.InvalidExclusionWildcard.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 SyntaxError: The limit format of the data schema is incorrect. 的本地化字符串。
        /// </summary>
        internal static string Schema_InvalidLimitFormat_Message {
            get {
                return ResourceManager.GetString("Schema.InvalidLimitFormat.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 SyntaxError: The limit &apos;{0}&apos; of the data schema is invalid or overflowed. 的本地化字符串。
        /// </summary>
        internal static string Schema_InvalidOrOverflowedLimit_Message {
            get {
                return ResourceManager.GetString("Schema.InvalidOrOverflowedLimit.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 SyntaxError: The limit of the data schema contains &apos;{0}&apos; illegal character. 的本地化字符串。
        /// </summary>
        internal static string Schema_LimitIllegalCharacter_Message {
            get {
                return ResourceManager.GetString("Schema.LimitIllegalCharacter.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 SyntaxError: Expected an exclusion member identifier after the period in the data schema, but found &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string Schema_MissingExclusionMemberAfterPeriod_Message {
            get {
                return ResourceManager.GetString("Schema.MissingExclusionMemberAfterPeriod.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 SyntaxError: Expected an identifier before the period in the data schema. 的本地化字符串。
        /// </summary>
        internal static string Schema_MissingIdentifierBeforePeriod_Message {
            get {
                return ResourceManager.GetString("Schema.MissingIdentifierBeforePeriod.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 SyntaxError: Expected limit in the data schema, but missing. 的本地化字符串。
        /// </summary>
        internal static string Schema_MissingLimit_Message {
            get {
                return ResourceManager.GetString("Schema.MissingLimit.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 SyntaxError: Expected a member identifier after the period in the data schema, but found &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string Schema_MissingMemberAfterPeriod_Message {
            get {
                return ResourceManager.GetString("Schema.MissingMemberAfterPeriod.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 SyntaxError: Expected a member identifier before the period in the data schema. 的本地化字符串。
        /// </summary>
        internal static string Schema_MissingMemberBeforePeriod_Message {
            get {
                return ResourceManager.GetString("Schema.MissingMemberBeforePeriod.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 SyntaxError: Expected sorting field in the data schema, but missing. 的本地化字符串。
        /// </summary>
        internal static string Schema_MissingSortingField_Message {
            get {
                return ResourceManager.GetString("Schema.MissingSortingField.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 SyntaxError: Expected sorting fields in the data schema, but missing. 的本地化字符串。
        /// </summary>
        internal static string Schema_MissingSortingFields_Message {
            get {
                return ResourceManager.GetString("Schema.MissingSortingFields.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 SyntaxError: The sorting field of the data schema contains &apos;{0}&apos; illegal character. 的本地化字符串。
        /// </summary>
        internal static string Schema_SortingFieldIllegalCharacter_Message {
            get {
                return ResourceManager.GetString("Schema.SortingFieldIllegalCharacter.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 SyntaxError: The sorting field of the data schema cannot start with a digit. 的本地化字符串。
        /// </summary>
        internal static string Schema_SortingFieldStartsWithDigit_Message {
            get {
                return ResourceManager.GetString("Schema.SortingFieldStartsWithDigit.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 SyntaxError: The data schema contains an unclosed member block. 的本地化字符串。
        /// </summary>
        internal static string Schema_UnclosedMemberBlock_Message {
            get {
                return ResourceManager.GetString("Schema.UnclosedMemberBlock.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 ParsingError: The &apos;{0}&apos; member of the data schema is unrecognized. 的本地化字符串。
        /// </summary>
        internal static string Schema_UnrecognizedMember_Message {
            get {
                return ResourceManager.GetString("Schema.UnrecognizedMember.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The selected link target does not exist. 的本地化字符串。
        /// </summary>
        internal static string Searcher_LinkTargetMissing_Message {
            get {
                return ResourceManager.GetString("Searcher.LinkTargetMissing.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Parent segments cannot follow a wildcard segment. 的本地化字符串。
        /// </summary>
        internal static string Searcher_ParentAfterWildcard_Message {
            get {
                return ResourceManager.GetString("Searcher.ParentAfterWildcard.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The search pattern must be relative to the directory. 的本地化字符串。
        /// </summary>
        internal static string Searcher_RelativePatternRequired_Message {
            get {
                return ResourceManager.GetString("Searcher.RelativePatternRequired.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The verification code generation operation is being called too frequently. Please wait a moment and try again later. 的本地化字符串。
        /// </summary>
        internal static string SecretGenerateTooFrequently_Message {
            get {
                return ResourceManager.GetString("SecretGenerateTooFrequently.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The secret argument contains illegal characters. 的本地化字符串。
        /// </summary>
        internal static string Secretor_InvalidArgument_Message {
            get {
                return ResourceManager.GetString("Secretor.InvalidArgument.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Invalid captch format. 的本地化字符串。
        /// </summary>
        internal static string Secretor_InvalidCaptcha_Message {
            get {
                return ResourceManager.GetString("Secretor.InvalidCaptcha.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Invalid secret pattern. 的本地化字符串。
        /// </summary>
        internal static string Secretor_InvalidPattern_Message {
            get {
                return ResourceManager.GetString("Secretor.InvalidPattern.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The account has been disabled. 的本地化字符串。
        /// </summary>
        internal static string Security_AccountDisabled_Message {
            get {
                return ResourceManager.GetString("Security.AccountDisabled.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Your account has been suspended, possibly due to too many failed verification attempts. 的本地化字符串。
        /// </summary>
        internal static string Security_AccountSuspended_Message {
            get {
                return ResourceManager.GetString("Security.AccountSuspended.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The account has not yet been approved. 的本地化字符串。
        /// </summary>
        internal static string Security_AccountUnapproved_Message {
            get {
                return ResourceManager.GetString("Security.AccountUnapproved.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The specified name cannot be a built-in name. 的本地化字符串。
        /// </summary>
        internal static string Security_BuiltinName_Message {
            get {
                return ResourceManager.GetString("Security.BuiltinName.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Access denied. Your account is not authorized to access the current resource. 的本地化字符串。
        /// </summary>
        internal static string Security_Forbidden_Message {
            get {
                return ResourceManager.GetString("Security.Forbidden.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Invalid identity identifier. 的本地化字符串。
        /// </summary>
        internal static string Security_InvalidIdentity_Message {
            get {
                return ResourceManager.GetString("Security.InvalidIdentity.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Invalid password. 的本地化字符串。
        /// </summary>
        internal static string Security_InvalidPassword_Message {
            get {
                return ResourceManager.GetString("Security.InvalidPassword.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Verification successful. 的本地化字符串。
        /// </summary>
        internal static string Security_Succeed_Message {
            get {
                return ResourceManager.GetString("Security.Succeed.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Other unknown security reasons. 的本地化字符串。
        /// </summary>
        internal static string Security_Unknown_Message {
            get {
                return ResourceManager.GetString("Security.Unknown.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The serialization options is immutable. 的本地化字符串。
        /// </summary>
        internal static string Serialization_Immutable_Message {
            get {
                return ResourceManager.GetString("Serialization.Immutable.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Invalid member type. 的本地化字符串。
        /// </summary>
        internal static string ServiceInjector_InvalidMemberType_Message {
            get {
                return ResourceManager.GetString("ServiceInjector.InvalidMemberType.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 An application name is required and must not contain reserved characters. 的本地化字符串。
        /// </summary>
        internal static string Services_ApplicationVersion_ApplicationNameInvalid_Message {
            get {
                return ResourceManager.GetString("Services.ApplicationVersion.ApplicationNameInvalid.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 A bare version number was expected. 的本地化字符串。
        /// </summary>
        internal static string Services_ApplicationVersion_BareVersionRequired_Message {
            get {
                return ResourceManager.GetString("Services.ApplicationVersion.BareVersionRequired.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The application version and named editions are mutually exclusive. 的本地化字符串。
        /// </summary>
        internal static string Services_ApplicationVersion_Conflict_Message {
            get {
                return ResourceManager.GetString("Services.ApplicationVersion.Conflict.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The edition name is duplicated. 的本地化字符串。
        /// </summary>
        internal static string Services_ApplicationVersion_EditionDuplicated_Message {
            get {
                return ResourceManager.GetString("Services.ApplicationVersion.EditionDuplicated.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The edition section header is invalid. 的本地化字符串。
        /// </summary>
        internal static string Services_ApplicationVersion_EditionHeaderInvalid_Message {
            get {
                return ResourceManager.GetString("Services.ApplicationVersion.EditionHeaderInvalid.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 An edition section header was expected. 的本地化字符串。
        /// </summary>
        internal static string Services_ApplicationVersion_EditionHeaderRequired_Message {
            get {
                return ResourceManager.GetString("Services.ApplicationVersion.EditionHeaderRequired.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 An initialized edition with a name and version number is required. 的本地化字符串。
        /// </summary>
        internal static string Services_ApplicationVersion_EditionInvalid_Message {
            get {
                return ResourceManager.GetString("Services.ApplicationVersion.EditionInvalid.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The edition name is invalid. 的本地化字符串。
        /// </summary>
        internal static string Services_ApplicationVersion_EditionNameInvalid_Message {
            get {
                return ResourceManager.GetString("Services.ApplicationVersion.EditionNameInvalid.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The edition has no version number. 的本地化字符串。
        /// </summary>
        internal static string Services_ApplicationVersion_EditionVersionRequired_Message {
            get {
                return ResourceManager.GetString("Services.ApplicationVersion.EditionVersionRequired.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The version number exceeds the formatting buffer. 的本地化字符串。
        /// </summary>
        internal static string Services_ApplicationVersion_FormattingBufferExceeded_Message {
            get {
                return ResourceManager.GetString("Services.ApplicationVersion.FormattingBufferExceeded.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 An application name and version information are required. 的本地化字符串。
        /// </summary>
        internal static string Services_ApplicationVersion_InformationRequired_Message {
            get {
                return ResourceManager.GetString("Services.ApplicationVersion.InformationRequired.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Invalid application version format at line {0}: {1} 的本地化字符串。
        /// </summary>
        internal static string Services_ApplicationVersion_InvalidFormat_Message {
            get {
                return ResourceManager.GetString("Services.ApplicationVersion.InvalidFormat.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The name is empty or contains characters reserved by the application version format. 的本地化字符串。
        /// </summary>
        internal static string Services_ApplicationVersion_NameInvalid_Message {
            get {
                return ResourceManager.GetString("Services.ApplicationVersion.NameInvalid.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 A name@version header cannot be followed by editions or additional content. 的本地化字符串。
        /// </summary>
        internal static string Services_ApplicationVersion_UnexpectedContent_Message {
            get {
                return ResourceManager.GetString("Services.ApplicationVersion.UnexpectedContent.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The application version number is invalid. 的本地化字符串。
        /// </summary>
        internal static string Services_ApplicationVersion_VersionInvalid_Message {
            get {
                return ResourceManager.GetString("Services.ApplicationVersion.VersionInvalid.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 An application version or at least one named edition is required. 的本地化字符串。
        /// </summary>
        internal static string Services_ApplicationVersion_VersionRequired_Message {
            get {
                return ResourceManager.GetString("Services.ApplicationVersion.VersionRequired.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Execute external commands through the system shell. 的本地化字符串。
        /// </summary>
        internal static string ShellCommand_Description {
            get {
                return ResourceManager.GetString("ShellCommand.Description", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Shell command 的本地化字符串。
        /// </summary>
        internal static string ShellCommand_Name {
            get {
                return ResourceManager.GetString("ShellCommand.Name", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Timeout for running commands, unit: milliseconds. 的本地化字符串。
        /// </summary>
        internal static string ShellCommand_Options_Timeout {
            get {
                return ResourceManager.GetString("ShellCommand.Options.Timeout", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Invalid sorting format. 的本地化字符串。
        /// </summary>
        internal static string Sorting_InvalidFormat_Message {
            get {
                return ResourceManager.GetString("Sorting.InvalidFormat.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Invalid type of the state context. 的本地化字符串。
        /// </summary>
        internal static string StateHandler_InvalidContext_Message {
            get {
                return ResourceManager.GetString("StateHandler.InvalidContext.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The destination stream does not support writing. 的本地化字符串。
        /// </summary>
        internal static string Stream_NotWritable_Message {
            get {
                return ResourceManager.GetString("Stream.NotWritable.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The string literal contains new-line symbol. 的本地化字符串。
        /// </summary>
        internal static string StringTokenizer_NewLine_Message {
            get {
                return ResourceManager.GetString("StringTokenizer.NewLine.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The committed event &apos;{0}&apos; cannot be dispatched because the transaction event channel is closed. 的本地化字符串。
        /// </summary>
        internal static string TransactionEventChannel_DispatchClosed {
            get {
                return ResourceManager.GetString("TransactionEventChannel.DispatchClosed", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The dispatching task of the transaction event channel &apos;{0}&apos; did not complete in a timely manner; the channel will be closed anyway. 的本地化字符串。
        /// </summary>
        internal static string TransactionEventChannel_DispatchingTimeout {
            get {
                return ResourceManager.GetString("TransactionEventChannel.DispatchingTimeout", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The specified &apos;{0}&apos; parameter must be a value type. 的本地化字符串。
        /// </summary>
        internal static string Type_ValueTypeRequired_Message {
            get {
                return ResourceManager.GetString("Type.ValueTypeRequired.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The type name or namespace must begin with a letter or an underscore. 的本地化字符串。
        /// </summary>
        internal static string TypeAlias_InvalidFirstCharacter_Message {
            get {
                return ResourceManager.GetString("TypeAlias.InvalidFirstCharacter.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The user name is empty. 的本地化字符串。
        /// </summary>
        internal static string UserService_EmptyName_Message {
            get {
                return ResourceManager.GetString("UserService.EmptyName.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Illegal format for stored password-answer. 的本地化字符串。
        /// </summary>
        internal static string UserService_InvalidStoredAnswer_Message {
            get {
                return ResourceManager.GetString("UserService.InvalidStoredAnswer.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Missing the required secretor. 的本地化字符串。
        /// </summary>
        internal static string UserService_MissingSecretor_Message {
            get {
                return ResourceManager.GetString("UserService.MissingSecretor.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The password questions and answers count is not equals. 的本地化字符串。
        /// </summary>
        internal static string UserService_PasswordAnswersCountMismatch_Message {
            get {
                return ResourceManager.GetString("UserService.PasswordAnswersCountMismatch.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The password answers verify failed. 的本地化字符串。
        /// </summary>
        internal static string UserService_PasswordAnswersFailed_Message {
            get {
                return ResourceManager.GetString("UserService.PasswordAnswersFailed.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Missing required worker of depends on. 的本地化字符串。
        /// </summary>
        internal static string WorkerCommand_MissingWorker_Message {
            get {
                return ResourceManager.GetString("WorkerCommand.MissingWorker.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Pause command 的本地化字符串。
        /// </summary>
        internal static string WorkerPauseCommand_Name {
            get {
                return ResourceManager.GetString("WorkerPauseCommand.Name", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Resume command 的本地化字符串。
        /// </summary>
        internal static string WorkerResumeCommand_Name {
            get {
                return ResourceManager.GetString("WorkerResumeCommand.Name", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Start command 的本地化字符串。
        /// </summary>
        internal static string WorkerStartCommand_Name {
            get {
                return ResourceManager.GetString("WorkerStartCommand.Name", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Force startup, even if the command is disabled. 的本地化字符串。
        /// </summary>
        internal static string WorkerStartCommand_Options_Force {
            get {
                return ResourceManager.GetString("WorkerStartCommand.Options.Force", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Paused 的本地化字符串。
        /// </summary>
        internal static string WorkerState_Paused {
            get {
                return ResourceManager.GetString("WorkerState.Paused", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Pausing 的本地化字符串。
        /// </summary>
        internal static string WorkerState_Pausing {
            get {
                return ResourceManager.GetString("WorkerState.Pausing", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Resuming 的本地化字符串。
        /// </summary>
        internal static string WorkerState_Resuming {
            get {
                return ResourceManager.GetString("WorkerState.Resuming", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Running 的本地化字符串。
        /// </summary>
        internal static string WorkerState_Running {
            get {
                return ResourceManager.GetString("WorkerState.Running", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Starting 的本地化字符串。
        /// </summary>
        internal static string WorkerState_Starting {
            get {
                return ResourceManager.GetString("WorkerState.Starting", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Stopped 的本地化字符串。
        /// </summary>
        internal static string WorkerState_Stopped {
            get {
                return ResourceManager.GetString("WorkerState.Stopped", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Stopping 的本地化字符串。
        /// </summary>
        internal static string WorkerState_Stopping {
            get {
                return ResourceManager.GetString("WorkerState.Stopping", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Stop command 的本地化字符串。
        /// </summary>
        internal static string WorkerStopCommand_Name {
            get {
                return ResourceManager.GetString("WorkerStopCommand.Name", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Role 的本地化字符串。
        /// </summary>
        internal static string Zongsoft_Security_Privileges_MemberType_Role {
            get {
                return ResourceManager.GetString("Zongsoft.Security.Privileges.MemberType.Role", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 User 的本地化字符串。
        /// </summary>
        internal static string Zongsoft_Security_Privileges_MemberType_User {
            get {
                return ResourceManager.GetString("Zongsoft.Security.Privileges.MemberType.User", resourceCulture);
            }
        }
    }
}
