//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zongsoft.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zongsoft.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Authentication failed. 的本地化字符串。
        /// </summary>
        internal static string AuthenticationException_Message {
            get {
                return ResourceManager.GetString("AuthenticationException.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Access denied: You do not have permission to access this resource. 的本地化字符串。
        /// </summary>
        internal static string AuthorizationException_Message {
            get {
                return ResourceManager.GetString("AuthorizationException.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear the display contents of the current terminal. 的本地化字符串。
        /// </summary>
        internal static string ClearCommand_Description {
            get {
                return ResourceManager.GetString("ClearCommand.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear command 的本地化字符串。
        /// </summary>
        internal static string ClearCommand_Name {
            get {
                return ResourceManager.GetString("ClearCommand.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} Execution failed. 的本地化字符串。
        /// </summary>
        internal static string Command_ExecutionFailed_Message {
            get {
                return ResourceManager.GetString("Command.ExecutionFailed.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} Execution successful. 的本地化字符串。
        /// </summary>
        internal static string Command_ExecutionSucceed_Message {
            get {
                return ResourceManager.GetString("Command.ExecutionSucceed.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Timeout 的本地化字符串。
        /// </summary>
        internal static string Command_Options_Timeout {
            get {
                return ResourceManager.GetString("Command.Options.Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Command error:  的本地化字符串。
        /// </summary>
        internal static string CommandError_Label {
            get {
                return ResourceManager.GetString("CommandError.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The specified &apos;{0}&apos; command was not found. 的本地化字符串。
        /// </summary>
        internal static string CommandNotFound_Message {
            get {
                return ResourceManager.GetString("CommandNotFound.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Application name 的本地化字符串。
        /// </summary>
        internal static string ConnectionSettings_Application {
            get {
                return ResourceManager.GetString("ConnectionSettings.Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Indicates the application identifier for the connection. 的本地化字符串。
        /// </summary>
        internal static string ConnectionSettings_Application_Description {
            get {
                return ResourceManager.GetString("ConnectionSettings.Application.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Character set 的本地化字符串。
        /// </summary>
        internal static string ConnectionSettings_Charset {
            get {
                return ResourceManager.GetString("ConnectionSettings.Charset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Indicates the name of the character set, such as UTF-8, GBK, etc. 的本地化字符串。
        /// </summary>
        internal static string ConnectionSettings_Charset_Description {
            get {
                return ResourceManager.GetString("ConnectionSettings.Charset.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Client name 的本地化字符串。
        /// </summary>
        internal static string ConnectionSettings_Client {
            get {
                return ResourceManager.GetString("ConnectionSettings.Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Indicates the client name of the connection program. 的本地化字符串。
        /// </summary>
        internal static string ConnectionSettings_Client_Description {
            get {
                return ResourceManager.GetString("ConnectionSettings.Client.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Database 的本地化字符串。
        /// </summary>
        internal static string ConnectionSettings_Database {
            get {
                return ResourceManager.GetString("ConnectionSettings.Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Indicates the name or identifier of the database to connect to. 的本地化字符串。
        /// </summary>
        internal static string ConnectionSettings_Database_Description {
            get {
                return ResourceManager.GetString("ConnectionSettings.Database.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Encoding scheme 的本地化字符串。
        /// </summary>
        internal static string ConnectionSettings_Encoding {
            get {
                return ResourceManager.GetString("ConnectionSettings.Encoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Indicates the text encoding scheme. 的本地化字符串。
        /// </summary>
        internal static string ConnectionSettings_Encoding_Description {
            get {
                return ResourceManager.GetString("ConnectionSettings.Encoding.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Group identifier 的本地化字符串。
        /// </summary>
        internal static string ConnectionSettings_Group {
            get {
                return ResourceManager.GetString("ConnectionSettings.Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Usually indicates the group to which a service or connection program belongs. 的本地化字符串。
        /// </summary>
        internal static string ConnectionSettings_Group_Description {
            get {
                return ResourceManager.GetString("ConnectionSettings.Group.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Instance name 的本地化字符串。
        /// </summary>
        internal static string ConnectionSettings_Instance {
            get {
                return ResourceManager.GetString("ConnectionSettings.Instance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Indicates the connection instance identifier. 的本地化字符串。
        /// </summary>
        internal static string ConnectionSettings_Instance_Description {
            get {
                return ResourceManager.GetString("ConnectionSettings.Instance.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password 的本地化字符串。
        /// </summary>
        internal static string ConnectionSettings_Password {
            get {
                return ResourceManager.GetString("ConnectionSettings.Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Indicates the password of the connected user. 的本地化字符串。
        /// </summary>
        internal static string ConnectionSettings_Password_Description {
            get {
                return ResourceManager.GetString("ConnectionSettings.Password.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Port number 的本地化字符串。
        /// </summary>
        internal static string ConnectionSettings_Port {
            get {
                return ResourceManager.GetString("ConnectionSettings.Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Indicates the server port number for the connection. 的本地化字符串。
        /// </summary>
        internal static string ConnectionSettings_Port_Description {
            get {
                return ResourceManager.GetString("ConnectionSettings.Port.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Provider 的本地化字符串。
        /// </summary>
        internal static string ConnectionSettings_Provider {
            get {
                return ResourceManager.GetString("ConnectionSettings.Provider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Indicates the connection provider identifier. 的本地化字符串。
        /// </summary>
        internal static string ConnectionSettings_Provider_Description {
            get {
                return ResourceManager.GetString("ConnectionSettings.Provider.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Server address 的本地化字符串。
        /// </summary>
        internal static string ConnectionSettings_Server {
            get {
                return ResourceManager.GetString("ConnectionSettings.Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Indicates the server address to connect to. For multiple target server addresses, they are typically separated by semicolons (;). 的本地化字符串。
        /// </summary>
        internal static string ConnectionSettings_Server_Description {
            get {
                return ResourceManager.GetString("ConnectionSettings.Server.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Timeout 的本地化字符串。
        /// </summary>
        internal static string ConnectionSettings_Timeout {
            get {
                return ResourceManager.GetString("ConnectionSettings.Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Indicates a connection timeout or a timeout for a related operation. 的本地化字符串。
        /// </summary>
        internal static string ConnectionSettings_Timeout_Description {
            get {
                return ResourceManager.GetString("ConnectionSettings.Timeout.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User name 的本地化字符串。
        /// </summary>
        internal static string ConnectionSettings_UserName {
            get {
                return ResourceManager.GetString("ConnectionSettings.UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Indicates the user name of the connection. 的本地化字符串。
        /// </summary>
        internal static string ConnectionSettings_UserName_Description {
            get {
                return ResourceManager.GetString("ConnectionSettings.UserName.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Credential error: The specified credential is invalid or has expired. 的本地化字符串。
        /// </summary>
        internal static string CredentialException_Message {
            get {
                return ResourceManager.GetString("CredentialException.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid data parameters or values. 的本地化字符串。
        /// </summary>
        internal static string DataArgumentException_Message {
            get {
                return ResourceManager.GetString("DataArgumentException.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data conflict: The value of {1} in data {0} is duplicated. 的本地化字符串。
        /// </summary>
        internal static string DataConflictException_Message {
            get {
                return ResourceManager.GetString("DataConflictException.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data constraint failure. 的本地化字符串。
        /// </summary>
        internal static string DataConstraintException_Message {
            get {
                return ResourceManager.GetString("DataConstraintException.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disabled 的本地化字符串。
        /// </summary>
        internal static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The configuration value at &quot;{0}&quot; cannot be converted to type &quot;{1}&quot;. 的本地化字符串。
        /// </summary>
        internal static string Error_FailedBinding {
            get {
                return ResourceManager.GetString("Error.FailedBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to create an instance of type &quot;{0}&quot;. 的本地化字符串。
        /// </summary>
        internal static string Error_FailedToActivate {
            get {
                return ResourceManager.GetString("Error.FailedToActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The configuration property name &quot;{0}&quot; is invalid. Located at: {1} 的本地化字符串。
        /// </summary>
        internal static string Error_IllegalConfigurationAttributeName {
            get {
                return ResourceManager.GetString("Error.IllegalConfigurationAttributeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The value &quot;{0}&quot; of the illegal configuration element cannot contain characters such as &apos;/&apos;, &apos;\&apos;, &apos;:&apos;, &apos;*&apos;, or &apos;?&apos;. Located at: {1} 的本地化字符串。
        /// </summary>
        internal static string Error_IllegalConfigurationKeyValue {
            get {
                return ResourceManager.GetString("Error.IllegalConfigurationKeyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The root node name &quot;{0}&quot; is invalid. {1} 的本地化字符串。
        /// </summary>
        internal static string Error_IllegalRootNodeName {
            get {
                return ResourceManager.GetString("Error.IllegalRootNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid option configuration file format. The configuration elements must be located within the &lt;option&gt; element. Located at: {0} 的本地化字符串。
        /// </summary>
        internal static string Error_InvalidOptionConfigurationFileFormat {
            get {
                return ResourceManager.GetString("Error.InvalidOptionConfigurationFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The specified &quot;{0}&quot; is an invalid unrecognized property. The type of unrecognized properties must be a dictionary with string keys. 的本地化字符串。
        /// </summary>
        internal static string Error_InvalidUnrecognizedProperty {
            get {
                return ResourceManager.GetString("Error.InvalidUnrecognizedProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Duplicate &quot;{0}&quot; key found. Located at: {1} 的本地化字符串。
        /// </summary>
        internal static string Error_KeyIsDuplicated {
            get {
                return ResourceManager.GetString("Error.KeyIsDuplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 XML namespaces are not supported. Located at: {0} 的本地化字符串。
        /// </summary>
        internal static string Error_NamespaceIsNotSupported {
            get {
                return ResourceManager.GetString("Error.NamespaceIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The &quot;{1}&quot; property of type &quot;{0}&quot; is not readable. 的本地化字符串。
        /// </summary>
        internal static string Error_PropertyCannotRead {
            get {
                return ResourceManager.GetString("Error.PropertyCannotRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There is no property named &quot;{1}&quot; in the &quot;{0}&quot; type. 的本地化字符串。
        /// </summary>
        internal static string Error_PropertyNotExists {
            get {
                return ResourceManager.GetString("Error.PropertyNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This operation cannot be repeated. 的本地化字符串。
        /// </summary>
        internal static string Error_RepeatedOperation {
            get {
                return ResourceManager.GetString("Error.RepeatedOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to create an instance of type &quot;{0}&quot; because multidimensional arrays are not supported. 的本地化字符串。
        /// </summary>
        internal static string Error_UnsupportedMultidimensionalArray {
            get {
                return ResourceManager.GetString("Error.UnsupportedMultidimensionalArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unsupported node type &quot;{0}&quot; detected. {1} 的本地化字符串。
        /// </summary>
        internal static string Error_UnsupportedNodeType {
            get {
                return ResourceManager.GetString("Error.UnsupportedNodeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error occurred:  的本地化字符串。
        /// </summary>
        internal static string ErrorOccurred_Label {
            get {
                return ResourceManager.GetString("ErrorOccurred.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do you want to quit? (Enter yes to quit) 的本地化字符串。
        /// </summary>
        internal static string ExitCommand_Confirm {
            get {
                return ResourceManager.GetString("ExitCommand.Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit the current application. 的本地化字符串。
        /// </summary>
        internal static string ExitCommand_Description {
            get {
                return ResourceManager.GetString("ExitCommand.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit command 的本地化字符串。
        /// </summary>
        internal static string ExitCommand_Name {
            get {
                return ResourceManager.GetString("ExitCommand.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit directly without prompting for confirmation. 的本地化字符串。
        /// </summary>
        internal static string ExitCommand_Options_Confirm {
            get {
                return ResourceManager.GetString("ExitCommand.Options.Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The specified &apos;{0}&apos; is an invalid command option. 的本地化字符串。
        /// </summary>
        internal static string InvalidCommandOption {
            get {
                return ResourceManager.GetString("InvalidCommandOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The specified &apos;{1}&apos; is an invalid &apos;{0}&apos; command option value. 的本地化字符串。
        /// </summary>
        internal static string InvalidCommandOptionValue {
            get {
                return ResourceManager.GetString("InvalidCommandOptionValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Row {0}, column {1}. 的本地化字符串。
        /// </summary>
        internal static string LinePositionInfo {
            get {
                return ResourceManager.GetString("LinePositionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This is a background service program that listens to message queues. It continuously polls the message queue in a blocking manner (It repeatedly calls the dequeue method of the message queue in a blocking manner). Once a message becomes available in the queue, it immediately dequeues the message and passes it to the executor in the listener for execution. 的本地化字符串。
        /// </summary>
        internal static string MessageQueueListener_Description {
            get {
                return ResourceManager.GetString("MessageQueueListener.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Message queue listener 的本地化字符串。
        /// </summary>
        internal static string MessageQueueListener_Title {
            get {
                return ResourceManager.GetString("MessageQueueListener.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The command option &apos;{0}&apos; is missing. A value must be provided for this option. 的本地化字符串。
        /// </summary>
        internal static string MissingCommandOption {
            get {
                return ResourceManager.GetString("MissingCommandOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Argument exception, possibly an unsupported argument value was passed. 的本地化字符串。
        /// </summary>
        internal static string OperationException_Argument_Message {
            get {
                return ResourceManager.GetString("OperationException.Argument.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The target could not be found, resulting in operation failure. 的本地化字符串。
        /// </summary>
        internal static string OperationException_Unfound_Message {
            get {
                return ResourceManager.GetString("OperationException.Unfound.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An unknown operation error has occurred. 的本地化字符串。
        /// </summary>
        internal static string OperationException_Unknown_Message {
            get {
                return ResourceManager.GetString("OperationException.Unknown.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to process the current operation. 的本地化字符串。
        /// </summary>
        internal static string OperationException_Unprocessed_Message {
            get {
                return ResourceManager.GetString("OperationException.Unprocessed.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failure to meet the necessary prerequisites resulted in the operation failing. 的本地化字符串。
        /// </summary>
        internal static string OperationException_Unsatisfied_Message {
            get {
                return ResourceManager.GetString("OperationException.Unsatisfied.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The current operation is not supported. 的本地化字符串。
        /// </summary>
        internal static string OperationException_Unsupported_Message {
            get {
                return ResourceManager.GetString("OperationException.Unsupported.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The verification code generation operation is being called too frequently. Please wait a moment and try again later. 的本地化字符串。
        /// </summary>
        internal static string SecretGenerateTooFrequently_Message {
            get {
                return ResourceManager.GetString("SecretGenerateTooFrequently.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The account has been disabled. 的本地化字符串。
        /// </summary>
        internal static string Security_AccountDisabled_Message {
            get {
                return ResourceManager.GetString("Security.AccountDisabled.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your account has been suspended, possibly due to too many failed verification attempts. 的本地化字符串。
        /// </summary>
        internal static string Security_AccountSuspended_Message {
            get {
                return ResourceManager.GetString("Security.AccountSuspended.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The account has not yet been approved. 的本地化字符串。
        /// </summary>
        internal static string Security_AccountUnapproved_Message {
            get {
                return ResourceManager.GetString("Security.AccountUnapproved.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Access denied. Your account is not authorized to access the current resource. 的本地化字符串。
        /// </summary>
        internal static string Security_Forbidden_Message {
            get {
                return ResourceManager.GetString("Security.Forbidden.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid identity identifier. 的本地化字符串。
        /// </summary>
        internal static string Security_InvalidIdentity_Message {
            get {
                return ResourceManager.GetString("Security.InvalidIdentity.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid password. 的本地化字符串。
        /// </summary>
        internal static string Security_InvalidPassword_Message {
            get {
                return ResourceManager.GetString("Security.InvalidPassword.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Verification successful. 的本地化字符串。
        /// </summary>
        internal static string Security_Succeed_Message {
            get {
                return ResourceManager.GetString("Security.Succeed.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Other unknown security reasons. 的本地化字符串。
        /// </summary>
        internal static string Security_Unknown_Message {
            get {
                return ResourceManager.GetString("Security.Unknown.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Execute external commands through the system shell. 的本地化字符串。
        /// </summary>
        internal static string ShellCommand_Description {
            get {
                return ResourceManager.GetString("ShellCommand.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shell command 的本地化字符串。
        /// </summary>
        internal static string ShellCommand_Name {
            get {
                return ResourceManager.GetString("ShellCommand.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Timeout for running commands, unit: milliseconds. 的本地化字符串。
        /// </summary>
        internal static string ShellCommand_Options_Timeout {
            get {
                return ResourceManager.GetString("ShellCommand.Options.Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tip: Press Ctrl+C to exit listening mode. 的本地化字符串。
        /// </summary>
        internal static string WorkerListenCommand_Prompt {
            get {
                return ResourceManager.GetString("WorkerListenCommand.Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Welcome to {0} listening mode. 的本地化字符串。
        /// </summary>
        internal static string WorkerListenCommand_Welcome {
            get {
                return ResourceManager.GetString("WorkerListenCommand.Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pause command 的本地化字符串。
        /// </summary>
        internal static string WorkerPauseCommand_Name {
            get {
                return ResourceManager.GetString("WorkerPauseCommand.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Resume command 的本地化字符串。
        /// </summary>
        internal static string WorkerResumeCommand_Name {
            get {
                return ResourceManager.GetString("WorkerResumeCommand.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start command 的本地化字符串。
        /// </summary>
        internal static string WorkerStartCommand_Name {
            get {
                return ResourceManager.GetString("WorkerStartCommand.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Force startup, even if the command is disabled. 的本地化字符串。
        /// </summary>
        internal static string WorkerStartCommand_Options_Force {
            get {
                return ResourceManager.GetString("WorkerStartCommand.Options.Force", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Paused 的本地化字符串。
        /// </summary>
        internal static string WorkerState_Paused {
            get {
                return ResourceManager.GetString("WorkerState.Paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pausing 的本地化字符串。
        /// </summary>
        internal static string WorkerState_Pausing {
            get {
                return ResourceManager.GetString("WorkerState.Pausing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Resuming 的本地化字符串。
        /// </summary>
        internal static string WorkerState_Resuming {
            get {
                return ResourceManager.GetString("WorkerState.Resuming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Running 的本地化字符串。
        /// </summary>
        internal static string WorkerState_Running {
            get {
                return ResourceManager.GetString("WorkerState.Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Starting 的本地化字符串。
        /// </summary>
        internal static string WorkerState_Starting {
            get {
                return ResourceManager.GetString("WorkerState.Starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stopped 的本地化字符串。
        /// </summary>
        internal static string WorkerState_Stopped {
            get {
                return ResourceManager.GetString("WorkerState.Stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stopping 的本地化字符串。
        /// </summary>
        internal static string WorkerState_Stopping {
            get {
                return ResourceManager.GetString("WorkerState.Stopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop command 的本地化字符串。
        /// </summary>
        internal static string WorkerStopCommand_Name {
            get {
                return ResourceManager.GetString("WorkerStopCommand.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Role 的本地化字符串。
        /// </summary>
        internal static string Zongsoft_Security_Privileges_MemberType_Role {
            get {
                return ResourceManager.GetString("Zongsoft.Security.Privileges.MemberType.Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User 的本地化字符串。
        /// </summary>
        internal static string Zongsoft_Security_Privileges_MemberType_User {
            get {
                return ResourceManager.GetString("Zongsoft.Security.Privileges.MemberType.User", resourceCulture);
            }
        }
    }
}
