<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<NoWarn>$(NoWarn);MSB3277;</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\Zongsoft.Net.csproj" />
	</ItemGroup>

	<Choose>
		<When Condition="$(Configuration)=='Debug'">
			<ItemGroup>
				<Reference Include="Zongsoft.Core">
					<HintPath>..\..\..\Zongsoft.Core\src\bin\$(Configuration)\$(TargetFramework)\Zongsoft.Core.dll</HintPath>
				</Reference>
			</ItemGroup>
		</When>
		<Otherwise>
			<ItemGroup>
				<PackageReference Include="Zongsoft.Core" VersionOverride="7.50.3" />
			</ItemGroup>
		</Otherwise>
	</Choose>

	<ItemGroup>
		<Compile Update="Properties\Resources.Designer.cs">
			<DesignTime>true</DesignTime>
			<AutoGen>true</AutoGen>
			<DependentUpon>Resources.resx</DependentUpon>
		</Compile>
		<EmbeddedResource Update="Properties\Resources.resx">
			<Generator>ResXFileCodeGenerator</Generator>
			<LastGenOutput>Resources.Designer.cs</LastGenOutput>
		</EmbeddedResource>
	</ItemGroup>
</Project>
