<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFrameworks>net8.0;net9.0;net10.0;</TargetFrameworks>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="BenchmarkDotNet" VersionOverride="0.15.8" />
		<PackageReference Include="BenchmarkDotNet.Annotations" VersionOverride="0.15.8" />
		<PackageReference Include="BenchmarkDotNet.Diagnostics.Windows" VersionOverride="0.15.8" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\src\Zongsoft.Core.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Compile Update="Properties\Resources.Designer.cs">
			<DesignTime>true</DesignTime>
			<AutoGen>true</AutoGen>
			<DependentUpon>Resources.resx</DependentUpon>
		</Compile>
		<EmbeddedResource Update="Properties\Resources.resx">
			<Generator>ResXFileCodeGenerator</Generator>
			<LastGenOutput>Resources.Designer.cs</LastGenOutput>
		</EmbeddedResource>
	</ItemGroup>
</Project>
