//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zongsoft.Messaging.Mqtt.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zongsoft.Messaging.Mqtt.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Session Clean 的本地化字符串。
        /// </summary>
        internal static string Mqtt_Settings_CleanSession {
            get {
                return ResourceManager.GetString("Mqtt.Settings.CleanSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Client 的本地化字符串。
        /// </summary>
        internal static string Mqtt_Settings_Client {
            get {
                return ResourceManager.GetString("Mqtt.Settings.Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Session Expiration 的本地化字符串。
        /// </summary>
        internal static string Mqtt_Settings_Expiration {
            get {
                return ResourceManager.GetString("Mqtt.Settings.Expiration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Group 的本地化字符串。
        /// </summary>
        internal static string Mqtt_Settings_Group {
            get {
                return ResourceManager.GetString("Mqtt.Settings.Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 KeepAlive 的本地化字符串。
        /// </summary>
        internal static string Mqtt_Settings_KeepAlive {
            get {
                return ResourceManager.GetString("Mqtt.Settings.KeepAlive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password 的本地化字符串。
        /// </summary>
        internal static string Mqtt_Settings_Password {
            get {
                return ResourceManager.GetString("Mqtt.Settings.Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Protocol Version 的本地化字符串。
        /// </summary>
        internal static string Mqtt_Settings_ProtocolVersion {
            get {
                return ResourceManager.GetString("Mqtt.Settings.ProtocolVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Server 的本地化字符串。
        /// </summary>
        internal static string Mqtt_Settings_Server {
            get {
                return ResourceManager.GetString("Mqtt.Settings.Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Timeout 的本地化字符串。
        /// </summary>
        internal static string Mqtt_Settings_Timeout {
            get {
                return ResourceManager.GetString("Mqtt.Settings.Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UserName 的本地化字符串。
        /// </summary>
        internal static string Mqtt_Settings_UserName {
            get {
                return ResourceManager.GetString("Mqtt.Settings.UserName", resourceCulture);
            }
        }
    }
}
