//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zongsoft.Data.MySql.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zongsoft.Data.MySql.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Allow Load Local Infile 的本地化字符串。
        /// </summary>
        internal static string MySql_Settings_AllowLoadLocalInfile {
            get {
                return ResourceManager.GetString("MySql.Settings.AllowLoadLocalInfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Local Infile in Path 的本地化字符串。
        /// </summary>
        internal static string MySql_Settings_AllowLoadLocalInfileInPath {
            get {
                return ResourceManager.GetString("MySql.Settings.AllowLoadLocalInfileInPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Allow Public Key Retrieval 的本地化字符串。
        /// </summary>
        internal static string MySql_Settings_AllowPublicKeyRetrieval {
            get {
                return ResourceManager.GetString("MySql.Settings.AllowPublicKeyRetrieval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Allow User Variables 的本地化字符串。
        /// </summary>
        internal static string MySql_Settings_AllowUserVariables {
            get {
                return ResourceManager.GetString("MySql.Settings.AllowUserVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Allow Zero DateTime 的本地化字符串。
        /// </summary>
        internal static string MySql_Settings_AllowZeroDateTime {
            get {
                return ResourceManager.GetString("MySql.Settings.AllowZeroDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Certificate Digest 的本地化字符串。
        /// </summary>
        internal static string MySql_Settings_CertificateDigest {
            get {
                return ResourceManager.GetString("MySql.Settings.CertificateDigest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Certificate File 的本地化字符串。
        /// </summary>
        internal static string MySql_Settings_CertificateFile {
            get {
                return ResourceManager.GetString("MySql.Settings.CertificateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Certificate Secret 的本地化字符串。
        /// </summary>
        internal static string MySql_Settings_CertificateSecret {
            get {
                return ResourceManager.GetString("MySql.Settings.CertificateSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Charset 的本地化字符串。
        /// </summary>
        internal static string MySql_Settings_Charset {
            get {
                return ResourceManager.GetString("MySql.Settings.Charset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Client 的本地化字符串。
        /// </summary>
        internal static string MySql_Settings_Client {
            get {
                return ResourceManager.GetString("MySql.Settings.Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Compression Enabled 的本地化字符串。
        /// </summary>
        internal static string MySql_Settings_Compressible {
            get {
                return ResourceManager.GetString("MySql.Settings.Compressible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connection Reset 的本地化字符串。
        /// </summary>
        internal static string MySql_Settings_ConnectionReset {
            get {
                return ResourceManager.GetString("MySql.Settings.ConnectionReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Convert Zero DateTime 的本地化字符串。
        /// </summary>
        internal static string MySql_Settings_ConvertZeroDateTime {
            get {
                return ResourceManager.GetString("MySql.Settings.ConvertZeroDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Database 的本地化字符串。
        /// </summary>
        internal static string MySql_Settings_Database {
            get {
                return ResourceManager.GetString("MySql.Settings.Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Integrated Security 的本地化字符串。
        /// </summary>
        internal static string MySql_Settings_IntegratedSecurity {
            get {
                return ResourceManager.GetString("MySql.Settings.IntegratedSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 KeepAlive 的本地化字符串。
        /// </summary>
        internal static string MySql_Settings_KeepAlive {
            get {
                return ResourceManager.GetString("MySql.Settings.KeepAlive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maximum Pool Size 的本地化字符串。
        /// </summary>
        internal static string MySql_Settings_MaximumPoolSize {
            get {
                return ResourceManager.GetString("MySql.Settings.MaximumPoolSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minimum Pool Size 的本地化字符串。
        /// </summary>
        internal static string MySql_Settings_MinimumPoolSize {
            get {
                return ResourceManager.GetString("MySql.Settings.MinimumPoolSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password 的本地化字符串。
        /// </summary>
        internal static string MySql_Settings_Password {
            get {
                return ResourceManager.GetString("MySql.Settings.Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pooling 的本地化字符串。
        /// </summary>
        internal static string MySql_Settings_Pooling {
            get {
                return ResourceManager.GetString("MySql.Settings.Pooling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Port 的本地化字符串。
        /// </summary>
        internal static string MySql_Settings_Port {
            get {
                return ResourceManager.GetString("MySql.Settings.Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Protocol 的本地化字符串。
        /// </summary>
        internal static string MySql_Settings_Protocol {
            get {
                return ResourceManager.GetString("MySql.Settings.Protocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Replication 的本地化字符串。
        /// </summary>
        internal static string MySql_Settings_Replication {
            get {
                return ResourceManager.GetString("MySql.Settings.Replication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Server 的本地化字符串。
        /// </summary>
        internal static string MySql_Settings_Server {
            get {
                return ResourceManager.GetString("MySql.Settings.Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SSL Mode 的本地化字符串。
        /// </summary>
        internal static string MySql_Settings_SslMode {
            get {
                return ResourceManager.GetString("MySql.Settings.SslMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Timeout 的本地化字符串。
        /// </summary>
        internal static string MySql_Settings_Timeout {
            get {
                return ResourceManager.GetString("MySql.Settings.Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User Name 的本地化字符串。
        /// </summary>
        internal static string MySql_Settings_UserName {
            get {
                return ResourceManager.GetString("MySql.Settings.UserName", resourceCulture);
            }
        }
    }
}
