### 应用列表
GET /Upgrading/Applications?page={{page}} HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{credentialId}}

### 应用查询
@name = {{$input 应用名称 $value: }}
@title = {{$input 应用标题 $value: }}
@enabled = {{$input 是否启用 $value: }}
POST /Upgrading/Applications/Query?page={{page}} HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{credentialId}}
Content-Type: application/json

{
	"Name": "{{name}}",
	"Title": "{{title}}",
	"Enabled": {{enabled}}
}

### 应用详情
@applicationId = {{$input 应用编号 $value: }}
GET /Upgrading/Applications/{{applicationId}} HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{credentialId}}

### 应用新增
@name = {{$input 应用名称 $value: }}
@title = {{$input 应用标题 $value: }}
@description = {{$input 应用描述 $value: }}
POST /Upgrading/Applications HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{credentialId}}
Content-Type: application/json

{
	"Name": "{{name}}",
	"Title": "{{title}}",
	"Enabled": true,
	"Description": "{{description}}"
}

### 应用修改
@applicationId = {{$input 应用编号 $value: }}
@title = {{$input 应用标题 $value: }}
@enabled = {{$input 是否启用 $value: }}
@description = {{$input 应用描述 $value: }}
PATCH /Upgrading/Applications/{{applicationId}} HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{credentialId}}
Content-Type: application/json

{
	"Title": "{{title}}",
	"Enabled": {{enabled}},
	"Description": "{{description}}"
}

### 应用删除
@applicationId = {{$input 应用编号 $value: }}
DELETE /Upgrading/Applications/{{applicationId}} HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{credentialId}}

### 应用数量
@enabled = {{$input 是否启用 $value: }}
POST /Upgrading/Applications/Count HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{credentialId}}
Content-Type: application/json

{
	"Enabled": {{enabled}}
}

### 应用版本列表
@applicationId = {{$input 应用编号 $value: }}
GET /Upgrading/Applications/{{applicationId}}/Editions?page={{page}} HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{credentialId}}

### 应用版本新增
@applicationId = {{$input 应用编号 $value: }}
@edition = {{$input 版本标识 $value: }}
@title = {{$input 版本标题 $value: }}
@description = {{$input 版本描述 $value: }}
POST /Upgrading/Applications/{{applicationId}}/Editions HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{credentialId}}
Content-Type: application/json

[
	{
		"Name": "{{edition}}",
		"Title": "{{title}}",
		"Enabled": true,
		"Licensed": false,
		"Description": "{{description}}"
	}
]

### 应用版本修改
@applicationId = {{$input 应用编号 $value: }}
@edition = {{$input 版本标识 $value: }}
@title = {{$input 版本标题 $value: }}
@enabled = {{$input 是否启用 $value: }}
@licensed = {{$input 是否授权 $value: }}
@description = {{$input 版本描述 $value: }}
PATCH /Upgrading/Applications/{{applicationId}}/Editions HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{credentialId}}
Content-Type: application/json

[
	{
		"Name": "{{edition}}",
		"Title": "{{title}}",
		"Enabled": {{enabled}},
		"Licensed": {{licensed}},
		"Description": "{{description}}"
	}
]
