### 实例列表
GET /Upgrading/Instances?page={{page}} HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{credentialId}}

### 实例查询
@instanceCode = {{$input 实例代号 $value: }}
@name = {{$input 实例名称 $value: }}
@tags = {{$input 标签集 $value: }}
POST /Upgrading/Instances/Query?page={{page}} HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{credentialId}}
Content-Type: application/json

{
	"InstanceCode": "{{instanceCode}}",
	"Name": "{{name}}",
	"Tags": "{{tags}}"
}

### 实例详情
@instanceId = {{$input 实例编号 $value: }}
GET /Upgrading/Instances/{{instanceId}} HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{credentialId}}

### 实例新增
@instanceCode = {{$input 实例代号 $value: }}
@name = {{$input 实例名称 $value: }}
@tags = {{$input 标签集 $value: }}
@profile = {{$input 配置信息 $value: }}
@description = {{$input 实例描述 $value: }}
POST /Upgrading/Instances HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{credentialId}}
Content-Type: application/json

{
	"InstanceCode": "{{instanceCode}}",
	"Name": "{{name}}",
	"Tags": "{{tags}}",
	"Profile": "{{profile}}",
	"Description": "{{description}}"
}

### 实例修改
@instanceId = {{$input 实例编号 $value: }}
@name = {{$input 实例名称 $value: }}
@tags = {{$input 标签集 $value: }}
@profile = {{$input 配置信息 $value: }}
@description = {{$input 实例描述 $value: }}
PATCH /Upgrading/Instances/{{instanceId}} HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{credentialId}}
Content-Type: application/json

{
	"Name": "{{name}}",
	"Tags": "{{tags}}",
	"Profile": "{{profile}}",
	"Description": "{{description}}"
}

### 实例删除
@instanceId = {{$input 实例编号 $value: }}
DELETE /Upgrading/Instances/{{instanceId}} HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{credentialId}}

### 实例发布跟踪查询
@instanceId = {{$input 实例编号 $value: }}
@releaseId = {{$input 发布编号 $value: }}
@phase = {{$input 发布阶段 $value: }}
POST /Upgrading/Instances/Tracings/Query?page={{page}} HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{credentialId}}
Content-Type: application/json

{
	"InstanceId": {{instanceId}},
	"ReleaseId": {{releaseId}},
	"Phase": "{{phase}}"
}

### 实例发布跟踪列表
@instanceId = {{$input 实例编号 $value: }}
GET /Upgrading/Instances/{{instanceId}}/Tracings?page={{page}} HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{credentialId}}

### 实例发布跟踪新增
@instanceId = {{$input 实例编号 $value: }}
@releaseId = {{$input 发布编号 $value: }}
@phase = {{$input 发布阶段 $value: }}
@message = {{$input 失败消息 $value: }}
@description = {{$input 阶段描述 $value: }}
POST /Upgrading/Instances/{{instanceId}}/Tracings HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{credentialId}}
Content-Type: application/json

[
	{
		"ReleaseId": {{releaseId}},
		"Phase": "{{phase}}",
		"Message": "{{message}}",
		"Description": "{{description}}"
	}
]
