### 实例查询
# @prompt instanceCode 实例代号
# @prompt name         实例名称
# @prompt tags         标签集
POST /Upgrading/Instances/Query?page={{page}} HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{$dotenv credentialId}}
Content-Type: application/json

{
	"InstanceCode": "{{instanceCode}}",
	"Name": "{{name}}",
	"Tags": "{{tags}}"
}

### 实例列表
GET /Upgrading/Instances?page={{page}} HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{$dotenv credentialId}}

### 实例详情
# @prompt instanceId 实例编号
GET /Upgrading/Instances/{{instanceId}} HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{$dotenv credentialId}}

### 实例新增
# @prompt instanceCode 实例代号
# @prompt name         实例名称
# @prompt tags         标签集
# @prompt profile      配置信息
# @prompt description  实例描述
POST /Upgrading/Instances HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{$dotenv credentialId}}
Content-Type: application/json

{
	"InstanceCode": "{{instanceCode}}",
	"Name": "{{name}}",
	"Tags": "{{tags}}",
	"Profile": "{{profile}}",
	"Description": "{{description}}"
}

### 实例修改
# @prompt instanceId  实例编号
# @prompt name        实例名称
# @prompt tags        标签集
# @prompt profile     配置信息
# @prompt description 实例描述
PATCH /Upgrading/Instances/{{instanceId}} HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{$dotenv credentialId}}
Content-Type: application/json

{
	"Name": "{{name}}",
	"Tags": "{{tags}}",
	"Profile": "{{profile}}",
	"Description": "{{description}}"
}

### 实例删除
# @prompt instanceId 实例编号
DELETE /Upgrading/Instances/{{instanceId}} HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{$dotenv credentialId}}

### 实例发布状态查询
# @prompt instanceId 实例编号
# @prompt releaseId  发布编号
# @prompt status     发布状态
POST /Upgrading/Instances/Publishings/Query?page={{page}} HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{$dotenv credentialId}}
Content-Type: application/json

{
	"InstanceId": {{instanceId}},
	"ReleaseId": {{releaseId}},
	"Status": {{status}}
}

### 实例发布状态列表
# @prompt instanceId 实例编号
GET /Upgrading/Instances/{{instanceId}}/Publishings?page={{page}} HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{$dotenv credentialId}}

### 实例发布状态新增
# @prompt instanceId   实例编号
# @prompt releaseId    发布编号
# @prompt status       发布状态
# @prompt message      失败消息
# @prompt description  状态描述
POST /Upgrading/Instances/{{instanceId}}/Publishings HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{$dotenv credentialId}}
Content-Type: application/json

[
	{
		"ReleaseId": {{releaseId}},
		"Status": {{status}},
		"Message": "{{message}}",
		"Description": "{{description}}"
	}
]
