### 发布查询
# @prompt name         应用名称
# @prompt edition      版本标识
# @prompt version      版本号
# @prompt platform     平台
# @prompt architecture 架构
# @prompt published    是否发布
# @prompt visible      是否可见
# @prompt deprecated   是否废弃
POST /Upgrading/Releases/Query?page={{$dotenv page}} HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{$dotenv credentialId}}
Content-Type: application/json

{
	"Name": "{{name}}",
	"Edition": "{{edition}}",
	"Version": "{{version}}",
	"Platform": "{{platform}}",
	"Architecture": "{{architecture}}",
	"Published": {{published}},
	"Visible": {{visible}},
	"Deprecated": {{deprecated}}
}

### 发布列表
GET /Upgrading/Releases?page={{$dotenv page}} HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{$dotenv credentialId}}

### 发布详情
# @prompt releaseId 发布编号
GET /Upgrading/Releases/{{releaseId}} HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{$dotenv credentialId}}

### 发布安装包上传
# @prompt releaseId    发布编号
# @prompt packagePath  安装包文件路径
POST /Upgrading/Releases/{{releaseId}}/Upload?overwrite=true HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{$dotenv credentialId}}
Content-Type: multipart/form-data; boundary=----ZongsoftUpgradingReleasePackage

------ZongsoftUpgradingReleasePackage
Content-Disposition: form-data; name="file"; filename="package.zip"
Content-Type: application/zip

< {{packagePath}}
------ZongsoftUpgradingReleasePackage--

### 发布 Manifest 导入
# @prompt manifestPath Manifest 文件路径
POST /Upgrading/Releases/Import?format=manifest HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{$dotenv credentialId}}
Content-Type: multipart/form-data; boundary=----ZongsoftUpgradingReleaseManifest

------ZongsoftUpgradingReleaseManifest
Content-Disposition: form-data; name="file"; filename="release.manifest"
Content-Type: application/xml

< {{manifestPath}}
------ZongsoftUpgradingReleaseManifest--

### 发布新增
# @prompt name             应用名称
# @prompt edition          版本标识
# @prompt version          版本号
# @prompt platform         平台
# @prompt architecture     架构
# @prompt title            发布标题
# @prompt summary          发布摘要
# @prompt evaluatorName    评估器名称
# @prompt evaluatorSetting 评估器设置
# @prompt description      发布描述
POST /Upgrading/Releases HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{$dotenv credentialId}}
Content-Type: application/json

{
	"Name": "{{name}}",
	"Edition": "{{edition}}",
	"Version": "{{version}}",
	"Kind": "Fully",
	"Mode": "Default",
	"Platform": "{{platform}}",
	"Architecture": "{{architecture}}",
	"Size": 0,
	"Deprecated": false,
	"Published": false,
	"Visible": true,
	"Title": "{{title}}",
	"Summary": "{{summary}}",
	"EvaluatorName": "{{evaluatorName}}",
	"EvaluatorSetting": "{{evaluatorSetting}}",
	"Description": "{{description}}"
}

### 发布修改
# @prompt releaseId        发布编号
# @prompt published        是否发布
# @prompt visible          是否可见
# @prompt deprecated       是否废弃
# @prompt evaluatorName    评估器名称
# @prompt evaluatorSetting 评估器设置
# @prompt summary          发布摘要
PATCH /Upgrading/Releases/{{releaseId}} HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{$dotenv credentialId}}
Content-Type: application/json

{
	"Published": {{published}},
	"Visible": {{visible}},
	"Deprecated": {{deprecated}},
	"EvaluatorName": "{{evaluatorName}}",
	"EvaluatorSetting": "{{evaluatorSetting}}",
	"Summary": "{{summary}}"
}

### 发布删除
# @prompt releaseId 发布编号
DELETE /Upgrading/Releases/{{releaseId}} HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{$dotenv credentialId}}

### 发布属性列表
# @prompt releaseId 发布编号
GET /Upgrading/Releases/{{releaseId}}/Properties?page={{$dotenv page}} HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{$dotenv credentialId}}

### 发布属性新增
# @prompt releaseId 发布编号
# @prompt name      属性名称
# @prompt type      属性类型
# @prompt value     属性值
POST /Upgrading/Releases/{{releaseId}}/Properties HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{$dotenv credentialId}}
Content-Type: application/json

[
	{
		"Name": "{{name}}",
		"Type": "{{type}}",
		"Value": "{{value}}"
	}
]

### 发布执行器列表
# @prompt releaseId 发布编号
GET /Upgrading/Releases/{{releaseId}}/Executors?page={{$dotenv page}} HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{$dotenv credentialId}}

### 发布执行器新增
# @prompt releaseId 发布编号
# @prompt serialId  执行序号
# @prompt event     执行事件
# @prompt command   执行命令
POST /Upgrading/Releases/{{releaseId}}/Executors HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{$dotenv credentialId}}
Content-Type: application/json

[
	{
		"SerialId": {{serialId}},
		"Event": "{{event}}",
		"Command": "{{command}}"
	}
]

### 发布状态查询
# @prompt releaseId  发布编号
# @prompt instanceId 实例编号
# @prompt status     发布状态
POST /Upgrading/Releases/Publishings/Query?page={{$dotenv page}} HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{$dotenv credentialId}}
Content-Type: application/json

{
	"ReleaseId": {{releaseId}},
	"InstanceId": {{instanceId}},
	"Status": "{{status}}"
}

### 发布状态列表
# @prompt releaseId 发布编号
GET /Upgrading/Releases/{{releaseId}}/Publishings?page={{$dotenv page}} HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{$dotenv credentialId}}

### 发布状态新增
# @prompt releaseId   发布编号
# @prompt instanceId  实例编号
# @prompt status      发布状态
# @prompt message     失败消息
# @prompt description 状态描述
POST /Upgrading/Releases/{{releaseId}}/Publishings HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{$dotenv credentialId}}
Content-Type: application/json

[
	{
		"InstanceId": {{instanceId}},
		"Status": "{{status}}",
		"Message": "{{message}}",
		"Description": "{{description}}"
	}
]
