### 列表查询
GET /Upgrading/Releases?page={{page}} HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{credentialId}}

### 复杂查询
@name = {{$input 应用名称 $value: }}
@edition = {{$input 版本标识 $value: }}
@version = {{$input 版本号 $value: }}
@platform = {{$input 平台 $value:windows }}
@architecture = {{$input 架构 $value:x64 }}
POST /Upgrading/Releases/Query?page={{page}} HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{credentialId}}
Content-Type: application/json

{
	"Name": "{{name}}",
	"Edition": "{{edition}}",
	"Version": "{{version}}",
	"Platform": "{{platform}}",
	"Architecture": "{{architecture}}"
}

### 详情查询(主键)
@releaseId = {{$input 发布编号 $value: }}
GET /Upgrading/Releases/{{releaseId}} HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{credentialId}}

### 发布新增
@name = {{$input 应用名称 $value: }}
@edition = {{$input 版本标识 $value: }}
@version = {{$input 版本号 $value: }}
@platform = {{$input 平台 $value:Windows }}
@architecture = {{$input 架构 $value:x64 }}
@title = {{$input 发布标题 $value: }}
@summary = {{$input 发布摘要 $value: }}
@evaluatorName = {{$input 评估器名称 $value: }}
@evaluatorSetting = {{$input 评估器设置 $value: }}
@description = {{$input 发布描述 $value: }}
POST /Upgrading/Releases HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{credentialId}}
Content-Type: application/json

{
	"Name": "{{name}}",
	"Edition": "{{edition}}",
	"Version": "{{version}}",
	"Kind": "Fully",
	"Mode": "Default",
	"Platform": "{{platform}}",
	"Architecture": "{{architecture}}",
	"Size": 0,
	"Deprecated": false,
	"Published": false,
	"Visible": true,
	"Title": "{{title}}",
	"Summary": "{{summary}}",
	"EvaluatorName": "{{evaluatorName}}",
	"EvaluatorSetting": "{{evaluatorSetting}}",
	"Description": "{{description}}"
}

### 发布安装包上传
@releaseId = {{$input 发布编号 $value: }}
@packagePath = {{$input 安装包文件路径 $value: }}
POST /Upgrading/Releases/{{releaseId}}/Upload?overwrite=true HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{credentialId}}
Content-Type: multipart/form-data; boundary=----ZongsoftUpgradingReleasePackage

------ZongsoftUpgradingReleasePackage
Content-Disposition: form-data; name="file"; filename="package.zip"
Content-Type: application/zip

< {{packagePath}}
------ZongsoftUpgradingReleasePackage--

### 发布 Manifest 导入
@manifestPath = {{$input Manifest 文件路径 $value: }}
POST /Upgrading/Releases/Import?format=manifest HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{credentialId}}
Content-Type: multipart/form-data; boundary=----ZongsoftUpgradingReleaseManifest

------ZongsoftUpgradingReleaseManifest
Content-Disposition: form-data; name="file"; filename="release.manifest"
Content-Type: application/xml

< {{manifestPath}}
------ZongsoftUpgradingReleaseManifest--

### 发布修改
@releaseId = {{$input 发布编号 $value: }}
@published = {{$input 是否发布 $value: }}
@visible = {{$input 是否可见 $value: }}
@deprecated = {{$input 是否废弃 $value: }}
@evaluatorName = {{$input 评估器名称 $value: }}
@evaluatorSetting = {{$input 评估器设置 $value: }}
@summary = {{$input 发布摘要 $value: }}
PATCH /Upgrading/Releases/{{releaseId}} HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{credentialId}}
Content-Type: application/json

{
	"Published": {{published}},
	"Visible": {{visible}},
	"Deprecated": {{deprecated}},
	"EvaluatorName": "{{evaluatorName}}",
	"EvaluatorSetting": "{{evaluatorSetting}}",
	"Summary": "{{summary}}"
}

### 发布删除
@releaseId = {{$input 发布编号 $value: }}
DELETE /Upgrading/Releases/{{releaseId}} HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{credentialId}}

### 发布属性列表
@releaseId = {{$input 发布编号 $value: }}
GET /Upgrading/Releases/{{releaseId}}/Properties?page={{page}} HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{credentialId}}

### 发布属性新增
@releaseId = {{$input 发布编号 $value: }}
@name = {{$input 属性名称 $value: }}
@type = {{$input 属性类型 $value: }}
@value = {{$input 属性值 $value: }}
POST /Upgrading/Releases/{{releaseId}}/Properties HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{credentialId}}
Content-Type: application/json

[
	{
		"Name": "{{name}}",
		"Type": "{{type}}",
		"Value": "{{value}}"
	}
]

### 发布执行器列表
@releaseId = {{$input 发布编号 $value: }}
GET /Upgrading/Releases/{{releaseId}}/Executors?page={{page}} HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{credentialId}}

### 发布执行器新增
@releaseId = {{$input 发布编号 $value: }}
@serialId = {{$input 执行序号 $value: }}
@event = {{$input 执行事件 $value: }}
@command = {{$input 执行命令 $value: }}
POST /Upgrading/Releases/{{releaseId}}/Executors HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{credentialId}}
Content-Type: application/json

[
	{
		"SerialId": {{serialId}},
		"Event": "{{event}}",
		"Command": "{{command}}"
	}
]

### 发布跟踪查询
@releaseId = {{$input 发布编号 $value: }}
@instanceId = {{$input 实例编号 $value: }}
@phase = {{$input 发布阶段 $value: }}
POST /Upgrading/Releases/Tracings/Query?page={{page}} HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{credentialId}}
Content-Type: application/json

{
	"ReleaseId": {{releaseId}},
	"InstanceId": {{instanceId}},
	"Phase": "{{phase}}"
}

### 发布跟踪列表
@releaseId = {{$input 发布编号 $value: }}
GET /Upgrading/Releases/{{releaseId}}/Tracings?page={{page}} HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{credentialId}}

### 发布跟踪新增
@releaseId = {{$input 发布编号 $value: }}
@instanceId = {{$input 实例编号 $value: }}
@phase = {{$input 发布阶段 $value: }}
@message = {{$input 失败消息 $value: }}
@description = {{$input 阶段描述 $value: }}
POST /Upgrading/Releases/{{releaseId}}/Tracings HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{credentialId}}
Content-Type: application/json

[
	{
		"InstanceId": {{instanceId}},
		"Phase": "{{phase}}",
		"Message": "{{message}}",
		"Description": "{{description}}"
	}
]
