//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zongsoft.Learning.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zongsoft.Learning.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Anomaly Detection 的本地化字符串。
        /// </summary>
        internal static string AnomalyDetection_Category {
            get {
                return ResourceManager.GetString("AnomalyDetection.Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Trainers and tasks specific to anomaly detection problems. 的本地化字符串。
        /// </summary>
        internal static string AnomalyDetection_Category_Description {
            get {
                return ResourceManager.GetString("AnomalyDetection.Category.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Binary Classification 的本地化字符串。
        /// </summary>
        internal static string BinaryClassification_Category {
            get {
                return ResourceManager.GetString("BinaryClassification.Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Trainers and tasks specific to binary classification problems. 的本地化字符串。
        /// </summary>
        internal static string BinaryClassification_Category_Description {
            get {
                return ResourceManager.GetString("BinaryClassification.Category.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clustering 的本地化字符串。
        /// </summary>
        internal static string Clustering_Category {
            get {
                return ResourceManager.GetString("Clustering.Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Trainers and tasks specific to clustering problems. 的本地化字符串。
        /// </summary>
        internal static string Clustering_Category_Description {
            get {
                return ResourceManager.GetString("Clustering.Category.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Components 的本地化字符串。
        /// </summary>
        internal static string Components_Category {
            get {
                return ResourceManager.GetString("Components.Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The catalog of components that will be used for model loading. 的本地化字符串。
        /// </summary>
        internal static string Components_Category_Description {
            get {
                return ResourceManager.GetString("Components.Category.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Forecasting 的本地化字符串。
        /// </summary>
        internal static string Forecasting_Category {
            get {
                return ResourceManager.GetString("Forecasting.Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Trainers and tasks specific to forecasting problems. 的本地化字符串。
        /// </summary>
        internal static string Forecasting_Category_Description {
            get {
                return ResourceManager.GetString("Forecasting.Category.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Multiclass Classification 的本地化字符串。
        /// </summary>
        internal static string MulticlassClassification_Category {
            get {
                return ResourceManager.GetString("MulticlassClassification.Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Trainers and tasks specific to multiclass classification problems. 的本地化字符串。
        /// </summary>
        internal static string MulticlassClassification_Category_Description {
            get {
                return ResourceManager.GetString("MulticlassClassification.Category.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ranking 的本地化字符串。
        /// </summary>
        internal static string Ranking_Category {
            get {
                return ResourceManager.GetString("Ranking.Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Trainers and tasks specific to ranking problems. 的本地化字符串。
        /// </summary>
        internal static string Ranking_Category_Description {
            get {
                return ResourceManager.GetString("Ranking.Category.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Regression 的本地化字符串。
        /// </summary>
        internal static string Regression_Category {
            get {
                return ResourceManager.GetString("Regression.Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Trainers and tasks specific to regression problems. 的本地化字符串。
        /// </summary>
        internal static string Regression_Category_Description {
            get {
                return ResourceManager.GetString("Regression.Category.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Categorical 的本地化字符串。
        /// </summary>
        internal static string Transforms_Categorical_Category {
            get {
                return ResourceManager.GetString("Transforms.Categorical.Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The list of operations over categorical data. 的本地化字符串。
        /// </summary>
        internal static string Transforms_Categorical_Category_Description {
            get {
                return ResourceManager.GetString("Transforms.Categorical.Category.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transforms 的本地化字符串。
        /// </summary>
        internal static string Transforms_Category {
            get {
                return ResourceManager.GetString("Transforms.Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The data processing operations. 的本地化字符串。
        /// </summary>
        internal static string Transforms_Category_Description {
            get {
                return ResourceManager.GetString("Transforms.Category.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Conversion 的本地化字符串。
        /// </summary>
        internal static string Transforms_Conversion_Category {
            get {
                return ResourceManager.GetString("Transforms.Conversion.Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The list of operations for data type conversion. 的本地化字符串。
        /// </summary>
        internal static string Transforms_Conversion_Category_Description {
            get {
                return ResourceManager.GetString("Transforms.Conversion.Category.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Feature Selection 的本地化字符串。
        /// </summary>
        internal static string Transforms_Features_Category {
            get {
                return ResourceManager.GetString("Transforms.Features.Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The list of operations for selecting features based on some criteria. 的本地化字符串。
        /// </summary>
        internal static string Transforms_Features_Category_Description {
            get {
                return ResourceManager.GetString("Transforms.Features.Category.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Text 的本地化字符串。
        /// </summary>
        internal static string Transforms_Text_Category {
            get {
                return ResourceManager.GetString("Transforms.Text.Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The list of operations for processing text data. 的本地化字符串。
        /// </summary>
        internal static string Transforms_Text_Category_Description {
            get {
                return ResourceManager.GetString("Transforms.Text.Category.Description", resourceCulture);
            }
        }
    }
}
