//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zongsoft.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zongsoft.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 {0}文件或目录是不存在的。 的本地化字符串。
        /// </summary>
        internal static string FileOrDirectoryNotExists {
            get {
                return ResourceManager.GetString("FileOrDirectoryNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看当前应用程序(进程)所有加载的程序集信息。 的本地化字符串。
        /// </summary>
        internal static string Text_AssemblyCommand_Description {
            get {
                return ResourceManager.GetString("Text.AssemblyCommand.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 程序集查看命令 的本地化字符串。
        /// </summary>
        internal static string Text_AssemblyCommand_Name {
            get {
                return ResourceManager.GetString("Text.AssemblyCommand.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法获得命令的操作目标：{0}。 的本地化字符串。
        /// </summary>
        internal static string Text_CannotObtainCommandTarget {
            get {
                return ResourceManager.GetString("Text.CannotObtainCommandTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 将输入参数转换成指定类型并返回。 的本地化字符串。
        /// </summary>
        internal static string Text_CastCommand_Description {
            get {
                return ResourceManager.GetString("Text.CastCommand.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 转换命令 的本地化字符串。
        /// </summary>
        internal static string Text_CastCommand_Name {
            get {
                return ResourceManager.GetString("Text.CastCommand.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 转换的字节数。 的本地化字符串。
        /// </summary>
        internal static string Text_CastCommand_Options_Count {
            get {
                return ResourceManager.GetString("Text.CastCommand.Options.Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 转换的文本编码。 的本地化字符串。
        /// </summary>
        internal static string Text_CastCommand_Options_Encoding {
            get {
                return ResourceManager.GetString("Text.CastCommand.Options.Encoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 转换的偏移量（起始字节数）。 的本地化字符串。
        /// </summary>
        internal static string Text_CastCommand_Options_Offset {
            get {
                return ResourceManager.GetString("Text.CastCommand.Options.Offset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 转换的类型。 的本地化字符串。
        /// </summary>
        internal static string Text_CastCommand_Options_Type {
            get {
                return ResourceManager.GetString("Text.CastCommand.Options.Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 命令 的本地化字符串。
        /// </summary>
        internal static string Text_Command {
            get {
                return ResourceManager.GetString("Text.Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有指定命令参数，请至少指定一个命令参数。 的本地化字符串。
        /// </summary>
        internal static string Text_Command_MissingArguments {
            get {
                return ResourceManager.GetString("Text.Command.MissingArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效的命令参数，参数个数必须为{0}。 的本地化字符串。
        /// </summary>
        internal static string Text_Command_RequiresCountOfArguments {
            get {
                return ResourceManager.GetString("Text.Command.RequiresCountOfArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 命令执行失败。 的本地化字符串。
        /// </summary>
        internal static string Text_CommandExecuteFailed {
            get {
                return ResourceManager.GetString("Text.CommandExecuteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 命令执行成功。 的本地化字符串。
        /// </summary>
        internal static string Text_CommandExecuteSucceed {
            get {
                return ResourceManager.GetString("Text.CommandExecuteSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 命令使用方法： 的本地化字符串。
        /// </summary>
        internal static string Text_CommandUsages {
            get {
                return ResourceManager.GetString("Text.CommandUsages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该命令提供获取当前程序的配置信息。 的本地化字符串。
        /// </summary>
        internal static string Text_ConfigurationCommand_Description {
            get {
                return ResourceManager.GetString("Text.ConfigurationCommand.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置命令 的本地化字符串。
        /// </summary>
        internal static string Text_ConfigurationCommand_Name {
            get {
                return ResourceManager.GetString("Text.ConfigurationCommand.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否以简化的方式显式。 的本地化字符串。
        /// </summary>
        internal static string Text_ConfigurationCommand_Options_Simplify {
            get {
                return ResourceManager.GetString("Text.ConfigurationCommand.Options.Simplify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该命令查看指定路径的配置信息。 的本地化字符串。
        /// </summary>
        internal static string Text_ConfigurationGetCommand_Description {
            get {
                return ResourceManager.GetString("Text.ConfigurationGetCommand.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取配置命令 的本地化字符串。
        /// </summary>
        internal static string Text_ConfigurationGetCommand_Name {
            get {
                return ResourceManager.GetString("Text.ConfigurationGetCommand.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已禁用 的本地化字符串。
        /// </summary>
        internal static string Text_Disabled {
            get {
                return ResourceManager.GetString("Text.Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输出命令的参数值。 的本地化字符串。
        /// </summary>
        internal static string Text_EchoCommand_Description {
            get {
                return ResourceManager.GetString("Text.EchoCommand.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 回声命令 的本地化字符串。
        /// </summary>
        internal static string Text_EchoCommand_Name {
            get {
                return ResourceManager.GetString("Text.EchoCommand.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件删除失败。 的本地化字符串。
        /// </summary>
        internal static string Text_FileDeleteFailed_Message {
            get {
                return ResourceManager.GetString("Text.FileDeleteFailed.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件删除成功。 的本地化字符串。
        /// </summary>
        internal static string Text_FileDeleteSucceed_Message {
            get {
                return ResourceManager.GetString("Text.FileDeleteSucceed.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定的“{0}”文件存在。 的本地化字符串。
        /// </summary>
        internal static string Text_FileExisted {
            get {
                return ResourceManager.GetString("Text.FileExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定的“{0}”文件不存在。 的本地化字符串。
        /// </summary>
        internal static string Text_FileNotExisted {
            get {
                return ResourceManager.GetString("Text.FileNotExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提供对命令的相关使用信息的命令。 的本地化字符串。
        /// </summary>
        internal static string Text_HelpCommand_Description {
            get {
                return ResourceManager.GetString("Text.HelpCommand.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帮助命令 的本地化字符串。
        /// </summary>
        internal static string Text_HelpCommand_Name {
            get {
                return ResourceManager.GetString("Text.HelpCommand.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提供Json相关操作的功能。 的本地化字符串。
        /// </summary>
        internal static string Text_JsonCommand_Description {
            get {
                return ResourceManager.GetString("Text.JsonCommand.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Json命令 的本地化字符串。
        /// </summary>
        internal static string Text_JsonCommand_Name {
            get {
                return ResourceManager.GetString("Text.JsonCommand.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定要序列化成员名称的命名规则。 的本地化字符串。
        /// </summary>
        internal static string Text_JsonCommand_Options_Casing {
            get {
                return ResourceManager.GetString("Text.JsonCommand.Options.Casing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定要序列化的最大深度，默认为3。 的本地化字符串。
        /// </summary>
        internal static string Text_JsonCommand_Options_Depth {
            get {
                return ResourceManager.GetString("Text.JsonCommand.Options.Depth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否启用Json序列化缩进格式。 的本地化字符串。
        /// </summary>
        internal static string Text_JsonCommand_Options_Indented {
            get {
                return ResourceManager.GetString("Text.JsonCommand.Options.Indented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否启用Json序列化元素类型信息。 的本地化字符串。
        /// </summary>
        internal static string Text_JsonCommand_Options_Typed {
            get {
                return ResourceManager.GetString("Text.JsonCommand.Options.Typed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有找到指定‘{0}’的命令。 的本地化字符串。
        /// </summary>
        internal static string Text_Message_CommandNotFound {
            get {
                return ResourceManager.GetString("Text.Message.CommandNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入要打开的文件路径： 的本地化字符串。
        /// </summary>
        internal static string Text_OpenFile_Prompt {
            get {
                return ResourceManager.GetString("Text.OpenFile.Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 可选的 的本地化字符串。
        /// </summary>
        internal static string Text_Optional {
            get {
                return ResourceManager.GetString("Text.Optional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清除指定队列中的所有元素。 的本地化字符串。
        /// </summary>
        internal static string Text_QueueClearCommand_Description {
            get {
                return ResourceManager.GetString("Text.QueueClearCommand.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清空队列 的本地化字符串。
        /// </summary>
        internal static string Text_QueueClearCommand_Name {
            get {
                return ResourceManager.GetString("Text.QueueClearCommand.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提供队列操作命令的队列。 的本地化字符串。
        /// </summary>
        internal static string Text_QueueCommand_Description {
            get {
                return ResourceManager.GetString("Text.QueueCommand.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前名为 &apos;{0}&apos; 队列，总计 {1} 个元素，其类型是：{2}
        ///队列信息：{3} 的本地化字符串。
        /// </summary>
        internal static string Text_QueueCommand_Message {
            get {
                return ResourceManager.GetString("Text.QueueCommand.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前队列命令缺少队列提供程序，因此无法选取指定名称的队列。 的本地化字符串。
        /// </summary>
        internal static string Text_QueueCommand_MissingQueueProvider {
            get {
                return ResourceManager.GetString("Text.QueueCommand.MissingQueueProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 队列命令 的本地化字符串。
        /// </summary>
        internal static string Text_QueueCommand_Name {
            get {
                return ResourceManager.GetString("Text.QueueCommand.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 从队列提供程序中没有找到指定名称为”{0}“的队列。 的本地化字符串。
        /// </summary>
        internal static string Text_QueueCommand_NotFoundQueue {
            get {
                return ResourceManager.GetString("Text.QueueCommand.NotFoundQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出队或者提取的项目个数。 的本地化字符串。
        /// </summary>
        internal static string Text_QueueCommand_Options_Count {
            get {
                return ResourceManager.GetString("Text.QueueCommand.Options.Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 消息队列名称。 的本地化字符串。
        /// </summary>
        internal static string Text_QueueCommand_Options_Name {
            get {
                return ResourceManager.GetString("Text.QueueCommand.Options.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定队列操作的队列名，多个队列名之间以逗号(,)分隔。 的本地化字符串。
        /// </summary>
        internal static string Text_QueueCommand_Options_Queues {
            get {
                return ResourceManager.GetString("Text.QueueCommand.Options.Queues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出队或入队操作循环执行的次数，默认值为1。如果在出队命令中该参数为负数则表示直至将队列出空为止。 的本地化字符串。
        /// </summary>
        internal static string Text_QueueCommand_Options_Round {
            get {
                return ResourceManager.GetString("Text.QueueCommand.Options.Round", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 返回指定队列的元素个数。 的本地化字符串。
        /// </summary>
        internal static string Text_QueueCountCommand_Description {
            get {
                return ResourceManager.GetString("Text.QueueCountCommand.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名为 &apos;{0}&apos; 队列，总计 {1} 个元素。 的本地化字符串。
        /// </summary>
        internal static string Text_QueueCountCommand_Message {
            get {
                return ResourceManager.GetString("Text.QueueCountCommand.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 队列数量命令 的本地化字符串。
        /// </summary>
        internal static string Text_QueueCountCommand_Name {
            get {
                return ResourceManager.GetString("Text.QueueCountCommand.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 将指定的参数加入到指定的队列中。 的本地化字符串。
        /// </summary>
        internal static string Text_QueueInCommand_Description {
            get {
                return ResourceManager.GetString("Text.QueueInCommand.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第 {0} 轮，入队 {1} 条记录，{2} 队列。 的本地化字符串。
        /// </summary>
        internal static string Text_QueueInCommand_Message {
            get {
                return ResourceManager.GetString("Text.QueueInCommand.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 入队命令 的本地化字符串。
        /// </summary>
        internal static string Text_QueueInCommand_Name {
            get {
                return ResourceManager.GetString("Text.QueueInCommand.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名为&apos;{0}&apos;的队列为空集。 的本地化字符串。
        /// </summary>
        internal static string Text_QueueIsEmpty {
            get {
                return ResourceManager.GetString("Text.QueueIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 从指定队列的队首移出元素。 的本地化字符串。
        /// </summary>
        internal static string Text_QueueOutCommand_Description {
            get {
                return ResourceManager.GetString("Text.QueueOutCommand.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第 {0} 轮，出队 {1} 条记录，{2} 队列。 的本地化字符串。
        /// </summary>
        internal static string Text_QueueOutCommand_Message {
            get {
                return ResourceManager.GetString("Text.QueueOutCommand.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出队命令 的本地化字符串。
        /// </summary>
        internal static string Text_QueueOutCommand_Name {
            get {
                return ResourceManager.GetString("Text.QueueOutCommand.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 返回指定队列的队首元素，但并不移除它。 的本地化字符串。
        /// </summary>
        internal static string Text_QueuePeekCommand_Description {
            get {
                return ResourceManager.GetString("Text.QueuePeekCommand.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看队首 的本地化字符串。
        /// </summary>
        internal static string Text_QueuePeekCommand_Name {
            get {
                return ResourceManager.GetString("Text.QueuePeekCommand.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 必须的 的本地化字符串。
        /// </summary>
        internal static string Text_Required {
            get {
                return ResourceManager.GetString("Text.Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入要保存的文件路径： 的本地化字符串。
        /// </summary>
        internal static string Text_SaveFile_Prompt {
            get {
                return ResourceManager.GetString("Text.SaveFile.Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提供验证码生成、校验等命令的宿主，通过该命令可更改验证码相关命令的验证码提供程序，譬如：services.get secret | secret 的本地化字符串。
        /// </summary>
        internal static string Text_SecretCommand_Description {
            get {
                return ResourceManager.GetString("Text.SecretCommand.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 秘密（验证码）宿主命令 的本地化字符串。
        /// </summary>
        internal static string Text_SecretCommand_Name {
            get {
                return ResourceManager.GetString("Text.SecretCommand.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生成一个或多个验证码，譬如：secret.generate -name:&apos;user.phone.change:100&apos; -pattern:#4 -timeout:15m 13800000001 13800000002 13800000003 的本地化字符串。
        /// </summary>
        internal static string Text_SecretGenerateCommand_Description {
            get {
                return ResourceManager.GetString("Text.SecretGenerateCommand.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生成秘密（验证码）命令 的本地化字符串。
        /// </summary>
        internal static string Text_SecretGenerateCommand_Name {
            get {
                return ResourceManager.GetString("Text.SecretGenerateCommand.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证码名称，该名称通常包含对应的目标标识（譬如：user.forget:100、user.email:100，其中数字100表示用户的唯一编号）。 的本地化字符串。
        /// </summary>
        internal static string Text_SecretGenerateCommand_Options_Name {
            get {
                return ResourceManager.GetString("Text.SecretGenerateCommand.Options.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证码生成模式，如果不指定或空字符串则生成6位数字；也可以表示生成验证码的规则，基本模式定义如下：
        ///- guid|uuid，表示生成一个GUID值
        ///- #{number}，表示生成{number}个的数字字符，譬如：#4
        ///- ?{number}，表示生成{number}个的含有字母或数字的字符，譬如：?8 的本地化字符串。
        /// </summary>
        internal static string Text_SecretGenerateCommand_Options_Pattern {
            get {
                return ResourceManager.GetString("Text.SecretGenerateCommand.Options.Pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 校验一个验证码，譬如：secret.verify -name:&apos;user.email:100&apos; 123456 的本地化字符串。
        /// </summary>
        internal static string Text_SecretVerifyCommand_Description {
            get {
                return ResourceManager.GetString("Text.SecretVerifyCommand.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 校验秘密（验证码）命令 的本地化字符串。
        /// </summary>
        internal static string Text_SecretVerifyCommand_Name {
            get {
                return ResourceManager.GetString("Text.SecretVerifyCommand.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证码名称，该名称通常包含对应的目标标识（譬如：user.forget:100、user.email:100，其中数字100表示用户的唯一编号）。 的本地化字符串。
        /// </summary>
        internal static string Text_SecretVerifyCommand_Options_Name {
            get {
                return ResourceManager.GetString("Text.SecretVerifyCommand.Options.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务器已经启动。 的本地化字符串。
        /// </summary>
        internal static string Text_ServerHasBeenStarted {
            get {
                return ResourceManager.GetString("Text.ServerHasBeenStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该命令提供切换指定服务供应程序工厂中的当前操作的供应程序，并显示所有服务提供程序的名称。
        ///如果不指定命令行的参数则显示所有命令提供程序的名称；否则将命令行参数所指定名称的服务提供程序(默认服务提供程序名为“.”)设置本命令操作的服务容器。 的本地化字符串。
        /// </summary>
        internal static string Text_ServicesCommand_Description {
            get {
                return ResourceManager.GetString("Text.ServicesCommand.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务命令 的本地化字符串。
        /// </summary>
        internal static string Text_ServicesCommand_Name {
            get {
                return ResourceManager.GetString("Text.ServicesCommand.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定名称为“{0}”的服务提供程序没有找到。 的本地化字符串。
        /// </summary>
        internal static string Text_ServicesCommand_NotFoundProvider {
            get {
                return ResourceManager.GetString("Text.ServicesCommand.NotFoundProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定的服务提供程序(服务容器)的名称。 的本地化字符串。
        /// </summary>
        internal static string Text_ServicesCommand_Options_Provider {
            get {
                return ResourceManager.GetString("Text.ServicesCommand.Options.Provider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该命令提供获取当前服务供应程序中的各种服务对象，并显式其信息。
        ///
        ///用法如下：
        ///
        ///services.get &amp;lt;service-name&amp;gt;
        ///	参数为要获取的服务名称，该名称为其在当前服务供应程序注册时声明的名称。
        ///
        ///services.get -contract:assemblyQualifiedName
        ///	-contract 选项为要获取的服务类型限定名。
        ///
        ///services.get -contract:assemblyQualifiedName parameter
        ///	-contract 选项为要获取的服务类型限定名；参数为解析时传入的参数。 的本地化字符串。
        /// </summary>
        internal static string Text_ServicesGetCommand_Description {
            get {
                return ResourceManager.GetString("Text.ServicesGetCommand.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务获取命令 的本地化字符串。
        /// </summary>
        internal static string Text_ServicesGetCommand_Name {
            get {
                return ResourceManager.GetString("Text.ServicesGetCommand.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 排序方式 的本地化字符串。
        /// </summary>
        internal static string Text_SortMode {
            get {
                return ResourceManager.GetString("Text.SortMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 升序 的本地化字符串。
        /// </summary>
        internal static string Text_SortMode_Asc {
            get {
                return ResourceManager.GetString("Text.SortMode.Asc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 降序 的本地化字符串。
        /// </summary>
        internal static string Text_SortMode_Desc {
            get {
                return ResourceManager.GetString("Text.SortMode.Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不排序 的本地化字符串。
        /// </summary>
        internal static string Text_SortMode_None {
            get {
                return ResourceManager.GetString("Text.SortMode.None", resourceCulture);
            }
        }
    }
}
