//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zongsoft.Data.ClickHouse.Properties
{
	using System;

	/// <summary>
	///   一个强类型的资源类，用于查找本地化的字符串等。
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class Resources
	{
		private static global::System.Resources.ResourceManager resourceMan;
		private static global::System.Globalization.CultureInfo resourceCulture;

		internal Resources() { }

		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager
		{
			get
			{
				if(object.ReferenceEquals(resourceMan, null))
					resourceMan = new global::System.Resources.ResourceManager("Zongsoft.Data.ClickHouse.Properties.Resources", typeof(Resources).Assembly);

				return resourceMan;
			}
		}

		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture
		{
			get => resourceCulture;
			set => resourceCulture = value;
		}

		internal static string ClickHouse_Settings_Compression => ResourceManager.GetString("ClickHouse.Settings.Compression", resourceCulture);
		internal static string ClickHouse_Settings_Database => ResourceManager.GetString("ClickHouse.Settings.Database", resourceCulture);
		internal static string ClickHouse_Settings_Password => ResourceManager.GetString("ClickHouse.Settings.Password", resourceCulture);
		internal static string ClickHouse_Settings_Path => ResourceManager.GetString("ClickHouse.Settings.Path", resourceCulture);
		internal static string ClickHouse_Settings_Port => ResourceManager.GetString("ClickHouse.Settings.Port", resourceCulture);
		internal static string ClickHouse_Settings_Protocol => ResourceManager.GetString("ClickHouse.Settings.Protocol", resourceCulture);
		internal static string ClickHouse_Settings_Server => ResourceManager.GetString("ClickHouse.Settings.Server", resourceCulture);
		internal static string ClickHouse_Settings_SessionId => ResourceManager.GetString("ClickHouse.Settings.SessionId", resourceCulture);
		internal static string ClickHouse_Settings_Timeout => ResourceManager.GetString("ClickHouse.Settings.Timeout", resourceCulture);
		internal static string ClickHouse_Settings_UseCustomDecimals => ResourceManager.GetString("ClickHouse.Settings.UseCustomDecimals", resourceCulture);
		internal static string ClickHouse_Settings_UseServerTimezone => ResourceManager.GetString("ClickHouse.Settings.UseServerTimezone", resourceCulture);
		internal static string ClickHouse_Settings_UseSession => ResourceManager.GetString("ClickHouse.Settings.UseSession", resourceCulture);
		internal static string ClickHouse_Settings_UserName => ResourceManager.GetString("ClickHouse.Settings.UserName", resourceCulture);
	}
}
