//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zongsoft.Data.SQLite.Properties
{
	using System;

	/// <summary>
	///   一个强类型的资源类，用于查找本地化的字符串等。
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class Resources
	{
		private static global::System.Resources.ResourceManager resourceMan;
		private static global::System.Globalization.CultureInfo resourceCulture;

		internal Resources() { }

		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager
		{
			get
			{
				if(object.ReferenceEquals(resourceMan, null))
					resourceMan = new global::System.Resources.ResourceManager("Zongsoft.Data.SQLite.Properties.Resources", typeof(Resources).Assembly);

				return resourceMan;
			}
		}

		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture
		{
			get => resourceCulture;
			set => resourceCulture = value;
		}

		internal static string SQLite_Settings_Cache => ResourceManager.GetString("SQLite.Settings.Cache", resourceCulture);
		internal static string SQLite_Settings_Database => ResourceManager.GetString("SQLite.Settings.Database", resourceCulture);
		internal static string SQLite_Settings_ForeignKeys => ResourceManager.GetString("SQLite.Settings.ForeignKeys", resourceCulture);
		internal static string SQLite_Settings_Mode => ResourceManager.GetString("SQLite.Settings.Mode", resourceCulture);
		internal static string SQLite_Settings_Password => ResourceManager.GetString("SQLite.Settings.Password", resourceCulture);
		internal static string SQLite_Settings_Pooling => ResourceManager.GetString("SQLite.Settings.Pooling", resourceCulture);
		internal static string SQLite_Settings_RecursiveTriggers => ResourceManager.GetString("SQLite.Settings.RecursiveTriggers", resourceCulture);
		internal static string SQLite_Settings_Timeout => ResourceManager.GetString("SQLite.Settings.Timeout", resourceCulture);
	}
}
