//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zongsoft.Data.SQLite.Properties {
    using System;


    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zongsoft.Data.SQLite.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   查找类似 Invalid &apos;{0}&apos; aggregate method. 的本地化字符串。
        /// </summary>
        internal static string ExpressionVisitor_AggregateInvalid_Message {
            get {
                return ResourceManager.GetString("ExpressionVisitor.AggregateInvalid.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Unsupported &apos;{0}&apos; data type. 的本地化字符串。
        /// </summary>
        internal static string ExpressionVisitor_DataTypeUnsupported_Message {
            get {
                return ResourceManager.GetString("ExpressionVisitor.DataTypeUnsupported.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The SQLite driver does not support the &apos;{0}&apos; sequence function. 的本地化字符串。
        /// </summary>
        internal static string ExpressionVisitor_SequenceUnsupported_Message {
            get {
                return ResourceManager.GetString("ExpressionVisitor.SequenceUnsupported.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Not supported &apos;{0}&apos; statement. 的本地化字符串。
        /// </summary>
        internal static string ExpressionVisitor_StatementUnsupported_Message {
            get {
                return ResourceManager.GetString("ExpressionVisitor.StatementUnsupported.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Cache Mode 的本地化字符串。
        /// </summary>
        internal static string SQLite_Settings_Cache {
            get {
                return ResourceManager.GetString("SQLite.Settings.Cache", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Database 的本地化字符串。
        /// </summary>
        internal static string SQLite_Settings_Database {
            get {
                return ResourceManager.GetString("SQLite.Settings.Database", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Foreign Keys 的本地化字符串。
        /// </summary>
        internal static string SQLite_Settings_ForeignKeys {
            get {
                return ResourceManager.GetString("SQLite.Settings.ForeignKeys", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Open Mode 的本地化字符串。
        /// </summary>
        internal static string SQLite_Settings_Mode {
            get {
                return ResourceManager.GetString("SQLite.Settings.Mode", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Password 的本地化字符串。
        /// </summary>
        internal static string SQLite_Settings_Password {
            get {
                return ResourceManager.GetString("SQLite.Settings.Password", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Pooling 的本地化字符串。
        /// </summary>
        internal static string SQLite_Settings_Pooling {
            get {
                return ResourceManager.GetString("SQLite.Settings.Pooling", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Recursive Triggers 的本地化字符串。
        /// </summary>
        internal static string SQLite_Settings_RecursiveTriggers {
            get {
                return ResourceManager.GetString("SQLite.Settings.RecursiveTriggers", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Timeout 的本地化字符串。
        /// </summary>
        internal static string SQLite_Settings_Timeout {
            get {
                return ResourceManager.GetString("SQLite.Settings.Timeout", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Missing required fields in the upsert statement. 的本地化字符串。
        /// </summary>
        internal static string UpsertStatement_MissingFields_Message {
            get {
                return ResourceManager.GetString("UpsertStatement.MissingFields.Message", resourceCulture);
            }
        }
    }
}
