//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zongsoft.Intelligences.Web.Properties {
    using System;


    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zongsoft.Intelligences.Web.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   查找类似 The specified &apos;{0}&apos; AI assistant was not found. 的本地化字符串。
        /// </summary>
        internal static string Chat_AssistantNotFound_Message {
            get {
                return ResourceManager.GetString("Chat.AssistantNotFound.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Unspecified the AI assistant. 的本地化字符串。
        /// </summary>
        internal static string Chat_AssistantRequired_Message {
            get {
                return ResourceManager.GetString("Chat.AssistantRequired.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Missing the chat content. 的本地化字符串。
        /// </summary>
        internal static string Chat_ContentRequired_Message {
            get {
                return ResourceManager.GetString("Chat.ContentRequired.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Unspecified the chat session identifier. 的本地化字符串。
        /// </summary>
        internal static string Chat_SessionIdRequired_Message {
            get {
                return ResourceManager.GetString("Chat.SessionIdRequired.Message", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The {0} feature is not present. 的本地化字符串。
        /// </summary>
        internal static string Http_FeatureRequired_Message {
            get {
                return ResourceManager.GetString("Http.FeatureRequired.Message", resourceCulture);
            }
        }
    }
}
