//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zongsoft.Messaging.Kafka.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zongsoft.Messaging.Kafka.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Client 的本地化字符串。
        /// </summary>
        internal static string Kafka_Settings_Client {
            get {
                return ResourceManager.GetString("Kafka.Settings.Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Compression Level 的本地化字符串。
        /// </summary>
        internal static string Kafka_Settings_CompressionLevel {
            get {
                return ResourceManager.GetString("Kafka.Settings.CompressionLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Compression Type 的本地化字符串。
        /// </summary>
        internal static string Kafka_Settings_CompressionType {
            get {
                return ResourceManager.GetString("Kafka.Settings.CompressionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Group 的本地化字符串。
        /// </summary>
        internal static string Kafka_Settings_Group {
            get {
                return ResourceManager.GetString("Kafka.Settings.Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Indicates the message group name, if not specified a random group name is generated by default. 的本地化字符串。
        /// </summary>
        internal static string Kafka_Settings_Group_Description {
            get {
                return ResourceManager.GetString("Kafka.Settings.Group.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Group Protocol 的本地化字符串。
        /// </summary>
        internal static string Kafka_Settings_GroupProtocol {
            get {
                return ResourceManager.GetString("Kafka.Settings.GroupProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Heartbeat 的本地化字符串。
        /// </summary>
        internal static string Kafka_Settings_Heartbeat {
            get {
                return ResourceManager.GetString("Kafka.Settings.Heartbeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Isolation Level 的本地化字符串。
        /// </summary>
        internal static string Kafka_Settings_IsolationLevel {
            get {
                return ResourceManager.GetString("Kafka.Settings.IsolationLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password 的本地化字符串。
        /// </summary>
        internal static string Kafka_Settings_Password {
            get {
                return ResourceManager.GetString("Kafka.Settings.Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Security Protocol 的本地化字符串。
        /// </summary>
        internal static string Kafka_Settings_SecurityProtocol {
            get {
                return ResourceManager.GetString("Kafka.Settings.SecurityProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Server 的本地化字符串。
        /// </summary>
        internal static string Kafka_Settings_Server {
            get {
                return ResourceManager.GetString("Kafka.Settings.Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Indicates the address of the Kafka message queue server to connection, multiple addresses separated by commas are supported. 的本地化字符串。
        /// </summary>
        internal static string Kafka_Settings_Server_Description {
            get {
                return ResourceManager.GetString("Kafka.Settings.Server.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Timeout 的本地化字符串。
        /// </summary>
        internal static string Kafka_Settings_Timeout {
            get {
                return ResourceManager.GetString("Kafka.Settings.Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Topic 的本地化字符串。
        /// </summary>
        internal static string Kafka_Settings_Topic {
            get {
                return ResourceManager.GetString("Kafka.Settings.Topic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transaction Id 的本地化字符串。
        /// </summary>
        internal static string Kafka_Settings_TransactionId {
            get {
                return ResourceManager.GetString("Kafka.Settings.TransactionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transaction Timeout 的本地化字符串。
        /// </summary>
        internal static string Kafka_Settings_TransactionTimeout {
            get {
                return ResourceManager.GetString("Kafka.Settings.TransactionTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User Name 的本地化字符串。
        /// </summary>
        internal static string Kafka_Settings_UserName {
            get {
                return ResourceManager.GetString("Kafka.Settings.UserName", resourceCulture);
            }
        }
    }
}
