//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zongsoft.Data.MsSql.Properties
{
	using System;

	/// <summary>
	///   一个强类型的资源类，用于查找本地化的字符串等。
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class Resources
	{
		private static global::System.Resources.ResourceManager resourceMan;
		private static global::System.Globalization.CultureInfo resourceCulture;

		internal Resources() { }

		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager
		{
			get
			{
				if(object.ReferenceEquals(resourceMan, null))
					resourceMan = new global::System.Resources.ResourceManager("Zongsoft.Data.MsSql.Properties.Resources", typeof(Resources).Assembly);

				return resourceMan;
			}
		}

		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture
		{
			get => resourceCulture;
			set => resourceCulture = value;
		}

		internal static string MsSql_Settings_Client => ResourceManager.GetString("MsSql.Settings.Client", resourceCulture);
		internal static string MsSql_Settings_ConnectRetryCount => ResourceManager.GetString("MsSql.Settings.ConnectRetryCount", resourceCulture);
		internal static string MsSql_Settings_ConnectRetryInterval => ResourceManager.GetString("MsSql.Settings.ConnectRetryInterval", resourceCulture);
		internal static string MsSql_Settings_Database => ResourceManager.GetString("MsSql.Settings.Database", resourceCulture);
		internal static string MsSql_Settings_Enlist => ResourceManager.GetString("MsSql.Settings.Enlist", resourceCulture);
		internal static string MsSql_Settings_HostNameInCertificate => ResourceManager.GetString("MsSql.Settings.HostNameInCertificate", resourceCulture);
		internal static string MsSql_Settings_IntegratedSecurity => ResourceManager.GetString("MsSql.Settings.IntegratedSecurity", resourceCulture);
		internal static string MsSql_Settings_Language => ResourceManager.GetString("MsSql.Settings.Language", resourceCulture);
		internal static string MsSql_Settings_LoadBalanceTimeout => ResourceManager.GetString("MsSql.Settings.LoadBalanceTimeout", resourceCulture);
		internal static string MsSql_Settings_MaximumPoolSize => ResourceManager.GetString("MsSql.Settings.MaximumPoolSize", resourceCulture);
		internal static string MsSql_Settings_MinimumPoolSize => ResourceManager.GetString("MsSql.Settings.MinimumPoolSize", resourceCulture);
		internal static string MsSql_Settings_MultipleActiveResultSets => ResourceManager.GetString("MsSql.Settings.MultipleActiveResultSets", resourceCulture);
		internal static string MsSql_Settings_Password => ResourceManager.GetString("MsSql.Settings.Password", resourceCulture);
		internal static string MsSql_Settings_Pooling => ResourceManager.GetString("MsSql.Settings.Pooling", resourceCulture);
		internal static string MsSql_Settings_Replication => ResourceManager.GetString("MsSql.Settings.Replication", resourceCulture);
		internal static string MsSql_Settings_Server => ResourceManager.GetString("MsSql.Settings.Server", resourceCulture);
		internal static string MsSql_Settings_ServerCertificate => ResourceManager.GetString("MsSql.Settings.ServerCertificate", resourceCulture);
		internal static string MsSql_Settings_Timeout => ResourceManager.GetString("MsSql.Settings.Timeout", resourceCulture);
		internal static string MsSql_Settings_TrustServerCertificate => ResourceManager.GetString("MsSql.Settings.TrustServerCertificate", resourceCulture);
		internal static string MsSql_Settings_UserName => ResourceManager.GetString("MsSql.Settings.UserName", resourceCulture);
		internal static string MsSql_Settings_WorkstationId => ResourceManager.GetString("MsSql.Settings.WorkstationId", resourceCulture);
	}
}
