### 身份标识登录
# @name signin
# @prompt identity 身份标识
# @prompt password 登录密码
POST /Security/Authentication/Signin?scenario={{scenario}} HTTP/1.1
Host: {{host}}:{{port}}

{
    "Identity":"{{identity}}",
    "Password":"{{password}}"
}

###

@credentialId={{signin.response.body.$.credentialId}}
@renewalToken={{signin.response.body.$.renewalToken}}
@userId={{signin.response.body.$.identity.userId}}
@userName={{signin.response.body.$.identity.name}}
@namespace={{signin.response.body.$.identity.namespace}}
@email={{signin.response.body.$.identity.email}}
@phone={{signin.response.body.$.identity.phone}}

### 验证码登录
# 注：验证码登录需要先通过 Secret 方法获取身份验证码。
# @name signin
# @prompt token  令牌号
# @prompt secret 验证码
POST /Security/Authentication/Signin/Secret/{{token}}?scenario={{scenario}} HTTP/1.1
Host: {{host}}:{{port}}
Content-Type: text/plain

{{secret}}

###

@credentialId={{signin.response.body.$.credentialId}}
@renewalToken={{signin.response.body.$.renewalToken}}
@userId={{signin.response.body.$.identity.userId}}
@userName={{signin.response.body.$.identity.name}}
@namespace={{signin.response.body.$.identity.namespace}}
@email={{signin.response.body.$.identity.email}}
@phone={{signin.response.body.$.identity.phone}}

### 支付宝登录
# @name signin
# @prompt broker 代理号（支付宝）
# @prompt token  令牌值
POST /Security/Authentication/Signin/Alipay/broker:{{broker}}?scenario={{scenario}} HTTP/1.1
Host: {{host}}:{{port}}
Content-Type: text/plain

{{token}}

###

@credentialId={{signin.response.body.$.credentialId}}
@renewalToken={{signin.response.body.$.renewalToken}}
@userId={{signin.response.body.$.identity.userId}}
@userName={{signin.response.body.$.identity.name}}
@namespace={{signin.response.body.$.identity.namespace}}
@email={{signin.response.body.$.identity.email}}
@phone={{signin.response.body.$.identity.phone}}

### 微信小程序登录
# @prompt applet 小程序编号
# @prompt token  小程序令牌
POST /Security/Authentication/Signin/Wechat/applet:{{applet}}?scenario={{scenario}} HTTP/1.1
Host: {{host}}:{{port}}
Content-Type: text/plain

{{token}}

###

@credentialId={{signin.response.body.$.credentialId}}
@renewalToken={{signin.response.body.$.renewalToken}}
@userId={{signin.response.body.$.identity.userId}}
@userName={{signin.response.body.$.identity.name}}
@namespace={{signin.response.body.$.identity.namespace}}
@email={{signin.response.body.$.identity.email}}
@phone={{signin.response.body.$.identity.phone}}

### 微信公众号登录
# @prompt channel 公众号编号
# @prompt token   公众号令牌
POST /Security/Authentication/Signin/Wechat/channel:{{channel}}?scenario={{scenario}} HTTP/1.1
Host: {{host}}:{{port}}
Content-Type: text/plain

{{token}}

###

@credentialId={{signin.response.body.$.credentialId}}
@renewalToken={{signin.response.body.$.renewalToken}}
@userId={{signin.response.body.$.identity.userId}}
@userName={{signin.response.body.$.identity.name}}
@namespace={{signin.response.body.$.identity.namespace}}
@email={{signin.response.body.$.identity.email}}
@phone={{signin.response.body.$.identity.phone}}

### 续约
# @name renew
POST /Security/Authentication/Renew/{{renewalToken}} HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{credentialId}}

### 注销登出
# @name signout
POST /Security/Authentication/Signout HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{credentialId}}


### 人机识别生成(验证码)
# @name captcha
POST /Security/Captcha/authencode HTTP/1.1
Host: {{host}}:{{port}}

### 人机识别验证(验证码)
# @name captcha
# @prompt token 验证令牌
# @prompt code  验证码值
POST /Security/Captcha/authencode/Verify HTTP/1.1
Host: {{host}}:{{port}}
Content-Type: text/plain

{{token}}:{{code}}


### 安全验证（手机）
### 操作步骤：
### 1. 通过人机识别接口(Captcha)发起识别；
### 2. 通过人机识别接口(Captcha/Verify)进行验证；
### 3. 将人机识别方案(scheme)与验证令牌(即人机识别验证操作的返回结果)以冒号分隔，置于 X-Captcha 请求头。
# @name secret
# @prompt phone   手机号码
# @prompt channel 验证通道(message|voice)
# @prompt captcha 人机识别(scheme:token)
POST /Security/Authentication/Secret/phone:{{phone}}?channel={{channel}} HTTP/1.1
Host: {{host}}:{{port}}
X-Captcha: {{captcha}}

### 安全验证（邮箱）
### 操作步骤：
### 1. 通过人机识别接口(Captcha)发起识别；
### 2. 通过人机识别接口(Captcha/Verify)进行验证；
### 3. 将人机识别方案(scheme)与验证令牌(即人机识别验证操作的返回结果)以冒号分隔，置于 X-Captcha 请求头。
# @name secret
# @prompt email   邮箱地址
# @prompt captcha 人机识别(scheme:token)
POST /Security/Authentication/Secret/email:{{email}} HTTP/1.1
Host: {{host}}:{{port}}
X-Captcha: {{captcha}}

### 安全校验
# @name verify
# @prompt token  验证令牌
# @prompt code   校验码值
POST /Security/Authentication/Verify/{{token}} HTTP/1.1
Host: {{host}}:{{port}}
Content-Type: text/plain

{{code}}
