### 权限定义
GET /Security/Authorization HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{credentialId}}

### 权限定义（授权方案）
@scheme = {{$input 授权方案 $value: }}
GET /Security/Authorization/{{scheme}} HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{credentialId}}

### 最终授权（当前用户）
GET /Security/Authorization/Privileges HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{credentialId}}

### 最终授权（指定用户）
@id = {{$input 用户标识 $value:100 }}
GET /Security/Authorization/Privileges/user:{{id}} HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{credentialId}}

### 最终授权（指定角色）
@id = {{$input 角色标识 $value:1 }}
GET /Security/Authorization/Privileges/role:{{id}} HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{credentialId}}
