### 身份标识登录
# @name signin
@identity = {{$input 身份标识 $value:Administrator }}
@password = {{$password 登录密码 $value: }}
POST /Security/Authentication/Signin?scenario={{scenario}} HTTP/1.1
Host: {{host}}:{{port}}

{
    "Identity":"{{identity}}",
    "Password":"{{password}}"
}

{{
	await require("./authentication.js").saveCredential(response, environmentName, require("vscode"));
}}

### 验证码登录
# 注：验证码登录需要先通过 Secret 方法获取身份验证码。
# @name signin
@secretToken = {{$input 令牌号 $value: }}
@secretCode = {{$input 验证码 $value: }}
POST /Security/Authentication/Signin/Secret/{{secretToken}}?scenario={{scenario}} HTTP/1.1
Host: {{host}}:{{port}}
Content-Type: text/plain

{{secretCode}}

{{
	await require("./authentication.js").saveCredential(response, environmentName, require("vscode"));
}}

### 支付宝登录
# @name signin
@alipayBroker = {{$input 代理号（支付宝） $value: }}
@alipayToken = {{$input 令牌值 $value: }}
POST /Security/Authentication/Signin/Alipay/broker:{{alipayBroker}}?scenario={{scenario}} HTTP/1.1
Host: {{host}}:{{port}}
Content-Type: text/plain

{{alipayToken}}

{{
	await require("./authentication.js").saveCredential(response, environmentName, require("vscode"));
}}

### 微信小程序登录
@wechatApplet = {{$input 小程序编号 $value: }}
@wechatAppletToken = {{$input 小程序令牌 $value: }}
POST /Security/Authentication/Signin/Wechat/applet:{{wechatApplet}}?scenario={{scenario}} HTTP/1.1
Host: {{host}}:{{port}}
Content-Type: text/plain

{{wechatAppletToken}}

{{
	await require("./authentication.js").saveCredential(response, environmentName, require("vscode"));
}}

### 微信公众号登录
@wechatChannel = {{$input 公众号编号 $value: }}
@wechatChannelToken = {{$input 公众号令牌 $value: }}
POST /Security/Authentication/Signin/Wechat/channel:{{wechatChannel}}?scenario={{scenario}} HTTP/1.1
Host: {{host}}:{{port}}
Content-Type: text/plain

{{wechatChannelToken}}

{{
	await require("./authentication.js").saveCredential(response, environmentName, require("vscode"));
}}

### 续约
# @name renew
POST /Security/Authentication/Renew/{{renewalToken}} HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{credentialId}}

### 注销登出
# @name signout
POST /Security/Authentication/Signout HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{credentialId}}


### 人机识别生成(验证码)
# @name captcha
POST /Security/Captcha/authencode HTTP/1.1
Host: {{host}}:{{port}}

### 人机识别验证(验证码)
# @name captcha
@captchaToken = {{$input 验证令牌 $value: }}
@captchaCode = {{$input 验证码值 $value: }}
POST /Security/Captcha/authencode/Verify HTTP/1.1
Host: {{host}}:{{port}}
Content-Type: text/plain

{{captchaToken}}:{{captchaCode}}


### 安全验证（手机）
# 操作步骤：
# 1. 通过人机识别接口(Captcha)发起识别；
# 2. 通过人机识别接口(Captcha/Verify)进行验证；
# 3. 将人机识别方案(scheme)与验证令牌(即人机识别验证操作的返回结果)以冒号分隔，置于 X-Captcha 请求头。
# @name secret
@phoneNumber = {{$input 手机号码 $value: }}
@messageChannel = {{$input 验证通道(message|voice) $value:message }}
@phoneCaptcha = {{$input 人机识别(scheme:token) $value: }}
POST /Security/Authentication/Secret/phone:{{phoneNumber}}?channel={{messageChannel}} HTTP/1.1
Host: {{host}}:{{port}}
X-Captcha: {{phoneCaptcha}}

### 安全验证（邮箱）
# 操作步骤：
# 1. 通过人机识别接口(Captcha)发起识别；
# 2. 通过人机识别接口(Captcha/Verify)进行验证；
# 3. 将人机识别方案(scheme)与验证令牌(即人机识别验证操作的返回结果)以冒号分隔，置于 X-Captcha 请求头。
# @name secret
@emailAddress = {{$input 邮箱地址 $value: }}
@emailCaptcha = {{$input 人机识别(scheme:token) $value: }}
POST /Security/Authentication/Secret/email:{{emailAddress}} HTTP/1.1
Host: {{host}}:{{port}}
X-Captcha: {{emailCaptcha}}

### 安全校验
# @name verify
@verifyToken = {{$input 验证令牌 $value: }}
@verifyCode = {{$input 校验码值 $value: }}
POST /Security/Authentication/Verify/{{verifyToken}} HTTP/1.1
Host: {{host}}:{{port}}
Content-Type: text/plain

{{verifyCode}}
