### 权限列表
# @prompt id 角色编号
GET /Security/Roles/{{id}}/Privileges HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{$dotenv credentialId}}

### 设置权限
### 提示：如果授权模式为空(null)或撤回(Revoked)，表示删除该授权记录。
# @prompt id    角色编号
# @prompt name  权限标识
# @prompt mode  授权模式(Denied:拒绝,Granted:授予,Revoked:撤回)
PUT /Security/Roles/{{id}}/Privileges HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{$dotenv credentialId}}
Content-Type: application/json

[
	{
		"Name":"{{name}}",
		"Mode":"{{mode}}"
	}
]

### 权限过滤列表
# @prompt id 角色编号
GET /Security/Roles/{{id}}/Privileges/Filtering HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{$dotenv credentialId}}

### 设置权限过滤
### 提示：如果过滤表达式为空或空字符串，表示删除该授权记录。
# @prompt id     角色编号
# @prompt name   权限标识
# @prompt filter 过滤表达式
PUT /Security/Roles/{{id}}/Privileges/Filtering HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{$dotenv credentialId}}
Content-Type: application/json

[
	{
		"Name":"{{name}}",
		"Filter":"{{filter}}"
	}
]
