### 权限列表
# @prompt id 用户编号
GET /Security/Users/{{id}}/Privileges HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{$dotenv credentialId}}

### 设置权限
### 提示：如果授权模式为空(null)或撤回(Revoked)，表示删除该授权记录。
# @prompt id    用户编号
# @prompt name  权限标识
# @prompt mode  授权模式(Denied:拒绝,Granted:授予,Revoked:撤回)
PUT /Security/Users/{{id}}/Privileges HTTP/1.1
Host: {{host}}:{{port}}
Authorization: Credential {{$dotenv credentialId}}
Content-Type: application/json

[
	{
		"Name":"{{name}}",
		"Mode":"{{mode}}"
	}
]
